; Auto-converted mechanically from ../gw-basic/bimisc.asm
; Edit the converter or the generated source deliberately; do not hand-wave syntax changes.

; [ This translation created 10-Feb-83 by Version 4.3 ]
; .RADIX  8
%include "dwoem.inc"
; TITLE   BIMISC  BASIC Interpreter miscellaneous routines/WHG/PGA etc.
; .RADIX	10
%assign PC8A 0
%define LABEL PC8A
%assign TRSHHC 0
%assign NECPPC 0
%assign NNECBS 0
%assign ALPS 0
%assign ALPCPM 0
%assign OKI 0
%assign HAL 0
%assign TSHIBA 0
%assign CAN8 0
%define LTRACE ALPCPM ;trace output selectable
; Data Segment
extern ARYTAB
extern CURLIN
extern DATPTR
extern FRETOP
extern MEMSIZ
extern OLDLIN
extern OLDTXT
extern STREND
extern SUBFLG
extern SAVTXT
extern TEMPPT
extern TEMPST
extern TXTTAB
extern VALTYP
extern VARTAB
extern TEMP
extern TOPMEM
extern PRMLEN
extern PRMLN2
extern PRMSTK
extern FUNACT
extern NOFUNS
; End of data segment externals
; Code Segment ( terminated by END at bottom of file )
extern BRKTXT
extern CRDO
extern CRDONZ
extern ERROR
extern FADDS
extern FCERR
extern FCOMP
extern FNDFOR
extern FNDLIN
extern FRMEVL
extern INLIN
extern LINGET
extern MOVFM
extern MOVMF
extern MOVRM
extern NEWSTT
extern OVERR
extern PTRGET
extern SNERR
extern OUTDO
extern CHRCON
extern TMERR
extern USERR
extern ERRFIN
extern GETBYT
extern STPRDY
extern NFERR
extern INTID2
extern NXTCON
extern CHRGTR
extern GETYPR
extern VMOVE
extern FRQINT
extern IADD
extern ICOMP
extern FRMQNT
extern FRESTR
extern DEFTBL
extern OPTFLG
extern OPTVAL
global STOPRG
global TON
global TOFF
extern TRCFLG
extern ONEFLG
extern ONELIN
extern SAVSTK
extern NXTFLG
global CLEARC
global STOP
global ISLET
global ISLET2
global STKINI
global GETSTK
global SCRATH
global SCRTCH
global STPEND
global CONT
global ENDST
global GTMPRT
global RUNC
global STPEND
global ENDCON
global RESTORE
global STOP
global RESFIN
global STKERR
global REASON
global OMERR
global OMERRR
extern LINKER
;
; THIS ROUTINE IS USED TO MAKE SURE A CERTAIN NUMBER
; OF LOCATIONS REMAIN AVAILABLE FOR THE
; STACK. THE CALL IS :
;       MVI     C,NUMBER OF 2 BYTE ENTRIES NECESSARY
;       CALL    GETSTK
;
; THIS ROUTINE MUST BE CALLED BY ANY ROUTINE WHICH PUTS
; AN ARBITRARY AMOUNT OF STUFF ON THE STACK
; (I.E. ANY RECURSIVE ROUTINE LIKE FRMEVL)
; IT IS ALSO CALLED BY ROUTINES SUCH AS "GOSUB" AND "FOR"
; WHICH MAKE PERMANENT ENTRIES ON THE STACK
; ROUTINES WHICH MERELY USE AND FREE UP THE GUARANTEED
; NUMLEV STACK LOCATIONS NEED NOT CALL THIS
;
GETSTK:	PUSH	BX ;SAVE [H,L]
extern STKLOW
	MOV BX, [STKLOW] ;in GIO86, stack can grow down to STKLOW
	MOV	CH,0
	ADD	BX,CX
	ADD	BX,CX ;SEE IF WE CAN HAVE THIS MANY
;
; [H,L]= SOME ADDRESS
; [H,L] IS EXAMINED TO MAKE SURE AT LEAST NUMLEV
; LOCATIONS REMAIN BETWEEN IT AND THE TOP OF THE STACK
;
%define CONS1 256-(2*NUMLEV)
	MOV	AL,CONS1 ;SET [H,L]=-[H,L]-2*NUMLEV
	SUB	AL,BL
	MOV	BL,AL
	MOV	AL,255
	SBB	AL,BH
	MOV	BH,AL
	JB	OMERR ;IN CASE [H,L] WAS TOO BIG(MBM 3/18**)
;NOW SEE IF SP IS LARGER
	ADD	BX,SP ;IF SO, CARRY WILL BE SET
	POP	BX ;GET BACK ORIGINAL [H,L]
	JNB	$+3
	RET ;WAS OK?
;OMERR fixes program links (starting at TXTTAB), resets SAVSTK to TOPMEM-2
; and issues an Out-of-Memory error message
;
OMERR:
	CALL	LINKER ;Fix links incase OMERR was called after
;deleting a program line because user
;was attempting to replace it.
;ONLY IMPORTANT IN VERSIONS WHERE
;STACK CONTEXT SURVIVES OTHER ERRORS
	MOV BX, [TOPMEM]
;ELIMINATE ALL STACK CONTEXT TO FREE
	DEC	BX ; UP SOME MEMORY SPACE
	DEC	BX ;MAKE SURE THE FNDFOR STOPPER IS SAVED
	MOV [SAVSTK], BX ;PLACE STACK IS RESTORED FROM
OMERRR:
	MOV	DX,ERRC_ERROM ;"OUT OF MEMORY"
	JMP	ERROR
extern GARBA2
extern CHNFLG
REASON:
db 0o71
db 0o36
dw FRETOP ;CMP FRETOP,BX
	JNAE	$+3
	RET ;YES
	MOV AL, byte [CHNFLG]
	OR	AL,AL ;can't garbage collect if CHAINING
	JNZ	OMERR
	PUSH	CX ;SAVE ALL REGS
	PUSH	DX
	PUSH	BX
	CALL	GARBA2 ;DO A GARBAGE COLLECTION
	POP	BX ;RESTORE ALL REGS
	POP	DX
	POP	CX
db 0o71
db 0o36
dw FRETOP ;CMP FRETOP,BX
	JNAE	$+3
	RET ;YES
	JMP	OMERR ;NO, GIVE "OUT OF MEMORY BUT DONT TOUCH STACK
;
;PAGE
; SUBTTL NODSKS, SCRATCH (NEW), RUNC, CLEARC, STKINI, QINLIN
global NODSKS
NODSKS:
	XOR	AL,AL
;
; THE "NEW" COMMAND CLEARS THE PROGRAM TEXT AS WELL
; AS VARIABLE SPACE
;
SCRATH:	JZ	$+3
	RET ;MAKE SURE THERE IS A TERMINATOR
SCRTCH:
	MOV BX, [TXTTAB] ;GET POINTER TO START OF TEXT
	CALL	TOFF ;TURN OFF TRACE. SET [A]=0.
extern PROFLG
	MOV byte [PROFLG], AL ;NO LONGER A PROTECTED FILE
extern AUTFLG
	MOV byte [AUTFLG], AL ;CLEAR AUTO MODE
extern PTRFLG
	MOV byte [PTRFLG], AL ;SAY NO POINTERS EXIST
	MOV	byte [BX],AL ;SAVE AT END OFF TEXT
	INC	BX ;BUMP POINTER
	MOV	byte [BX],AL ;SAVE ZERO
	INC	BX ;BUMP POINTER
	MOV [VARTAB], BX ;NEW START OF VARIABLES
RUNC:
	MOV BX, [TXTTAB] ;POINT AT THE START OF TEXT
	DEC	BX
;
; CLEARC IS A SUBROUTINE WHICH INITIALIZES THE VARIABLE AND
; ARRAY SPACE BY RESETING ARYTAB [THE END OF SIMPLE VARIABLE SPACE]
; AND STREND [THE END OF ARRAY STORAGE]. IT FALLS INTO STKINI
; WHICH RESETS THE STACK. [H,L] IS PRESERVED.
;
CLEARC:
	MOV [TEMP], BX ;SAVE [H,L] IN TEMP
	CALL	INITRP ;INIT TRAP TABLE
extern GRPRST
	CALL	GRPRST ;Reset graphics
	CALL	INITRP ;Initialize trapping
extern SNDINI
	CALL	SNDINI ;Initialize SOUND & PLAY
extern MRGFLG
	MOV AL, byte [MRGFLG] ;DOING A CHAIN MERGE?
	OR	AL,AL ;TEST
	JNZ	LEVDTB ;LEAVE DEFAULT TABLE ALONE
	XOR	AL,AL
	MOV byte [OPTFLG], AL ;INDICATE NO "OPTION" HAS BEEN SEEN
	MOV byte [OPTVAL], AL ;DEFAULT TO "OPTION BASE 0"
	MOV	CH,26 ;INITIALIZE THE DEFAULT VALTYPE TABLE
	MOV	BX,DEFTBL ;POINT AT THE FIRST ENTRY
LOPDFT:
	MOV	byte [BX],4 ;LOOP 26 TIMES STORING A DEFAULT VALTYP
	INC	BX ;FOR SINGLE PRECISION
;COUNT OFF THE LETTERS
	DEC	CH
	JNZ	LOPDFT ;LOOP BACK, AND SETUP THE REST OF THE TABLE
LEVDTB:
extern RNDCOP
extern RNDX
extern MOVE
	MOV	DX,RNDCOP ;RESET THE RANDOM NUMBER GENERATOR
	MOV	BX,RNDX ;SEED IN RNDX
	CALL	MOVE
	XOR	AL,AL
	MOV byte [ONEFLG], AL ;RESET ON ERROR FLAG FOR RUNS
	MOV	BL,AL ;RESET ERROR LINE NUMBER
	MOV	BH,AL ;BY SETTING ONELIN=0.
	MOV [ONELIN], BX
	MOV [OLDTXT], BX ;MAKE CONTINUING IMPOSSIBLE
extern ERRLIN
	MOV [ERRLIN], BX ;Clear error line number
	MOV BX, [MEMSIZ]
extern CHNFLG
	MOV AL, byte [CHNFLG] ;ARE WE CHAINING?
	OR	AL,AL ;TEST
	JNZ	GODFRE ;FRETOP IS GOOD, LEAVE IT ALONE
	MOV [FRETOP], BX ;FREE UP STRING SPACE
GODFRE:	XOR	AL,AL ;MAKE SURE [A] IS ZERO, CC'S SET
	CALL	RESTORE ;RESTORE DATA
	MOV BX, [VARTAB] ;GET START OF VARIABLE SPACE
	MOV [ARYTAB], BX ;SAVE IN START OF ARRAY SPACE
	MOV [STREND], BX ;AND END OF VARIABLE STORAGE
extern CLSALL
	MOV AL, byte [MRGFLG] ;DOING CHAIN MERGE?
	OR	AL,AL
	JNZ	??L000
	CALL	CLSALL ;IF SO, DONT CLOSE FILES...
??L000:
extern NLONLY
	MOV AL, byte [NLONLY] ;GET LOAD FLAGS
	AND	AL,1 ;CURRENTLY LOADING?
	JNZ	CLRDS1 ;YES, LEAVE OTHERS OPEN
	MOV byte [NLONLY], AL ;ENABLE CLOSE ALL
CLRDS1:
;
; STKINI RESETS THE STACK POINTER ELIMINATING
; GOSUB & FOR CONTEXT.  STRING TEMPORARIES ARE FREED
; UP, SUBFLG IS RESET, CONTINUING IS DISALLOWED,
; AND A DUMMY ENTRY IS PUT ON THE STACK. THIS IS SO
; FNDFOR WILL ALWAYS FIND A NON-"FOR" ENTRY AT THE BOTTOM
; OF THE STACK. [A]=0 AND [D,E] IS PRESERVED.
;
STKINI:	POP	CX ;GET RETURN ADDRESS HERE
	MOV BX, [TOPMEM]
	DEC	BX ;TAKE INTO ACCOUNT FNDFOR STOPPER
	DEC	BX
	MOV [SAVSTK], BX ;MAKE SURE SAVSTK OK JUST IN CASE.
	INC	BX ;INCREMENT BACK FOR SPHL
	INC	BX
STKERR:
	MOV	SP,BX ;INITIALIZE STACK
	MOV	BX,TEMPST
	MOV [TEMPPT], BX ;INITIALIZE STRING TEMPORARIES
extern CLROVC
	CALL	CLROVC ;BACK TO NORMAL OVERFLOW PRINT MODE
extern FINPRT
	CALL	FINPRT ;CLEAR PTRFIL, OTHER I/O FLAGS
	XOR	AL,AL ;ZERO OUT A
	MOV	BH,AL ;ZERO OUT H
	MOV	BL,AL ;ZERO OUT L
	MOV [PRMLEN], BX ;FLAG NO ACTIVE PARAMETERS
	MOV byte [NOFUNS], AL ;INDICATE NO USER FUNCTIONS ACTIVE
	MOV [PRMLN2], BX ;NO PARAMETERS BEING BUILT
	MOV [FUNACT], BX ;SET NUMBER OF FUNCTIONS ACTIVE TO 0
	MOV [PRMSTK], BX ;AND NO PARAMETER BLOCKS ON THE STACK
	MOV byte [SUBFLG], AL ;ALLOW SUBSCRIPTS
	PUSH	BX ;PUT ZERO (NON $FOR,$GOSUB)
;ON THE STACK
	PUSH	CX ;PUT RETURN ADDRESS BACK ON
GTMPRT:	MOV BX, [TEMP] ;GET SAVED [H,L]
	RET
;PAGE
; SUBTTL DCOMPR, SYNCHR - REPLACEMENTS FOR COMPAR & SYNCHK IN RSTLES VERSION
global DCOMPR
DCOMPR:
	CMP	BX,DX
	RET
global SYNCHR
SYNCHR:
db 0o136 ;POP SI
db 0o213, 0o373 ;MOV DI,BX
db 0o374 ;CLD
db 0o56 ;BYTE COMPARED TO IS IN CODE SEGMENT
db 0o246 ;CMPC-IS CHAR THE RIGHT ONE?
db 0o126 ;PUSH SI
db 0o213, 0o337 ;MOV BX,DI
	JNZ	SYNERR ;GIVE ERROR IF CHARS DONT MATCH
	MOV	AL,byte [BX] ;GET IT
	CMP	AL,":" ;IS IT END OF STATMENT OR BIGGER
	JB	SYNCON ;GO TO CHRCON
	RET ;DONE
SYNCON:	JMP	CHRCON ;REST OF CHRGET
SYNERR:	JMP	SNERR ;IFE CYB
; SUBTTL TRAP ROUTINES - ON, OFF, STOP, INIT, REQUEST, FREE, RESET
;
;Trap flag bit definitions(Routines shift bits - don't change)
;
%assign T_ON 1 ;Trap on
%assign T_STOP 2 ;Trap stop
%assign T_REQ 4 ;Trap request
;TURN TRAP ON
;
global ONTRP
ONTRP:	CLI
	MOV	AL,byte [BX]
	AND	AL,T_REQ ;LEAVE REQUEST BIT
	OR	AL,T_ON ;ADD ON BIT
	CMP	AL,byte [BX]
	MOV	byte [BX],AL
	JZ	ONTRP0 ;NO CHANGE IN STATUS
	AND	AL,T_REQ
	JNZ	SETTP2 ;DELAYED TRAP REQUEST
ONTRP0:	STI
	RET
;TURN TRAP OFF
;
global OFFTRP
OFFTRP:	CLI
	MOV	AL,byte [BX]
	MOV	byte [BX],0
	JMP	FRECHK ;FREE OUTSTANDING REQUEST
;STOP TRAP
;
global STPTRP
STPTRP:	CLI
	MOV	AL,byte [BX]
	LAHF ; PUSH PSW
	XCHG	AL,AH
	PUSH	AX
	XCHG	AL,AH
	OR	AL,T_STOP
	MOV	byte [BX],AL
	POP	AX ; POP PSW
	XCHG	AL,AH
	SAHF
FRECHK:	XOR	AL,T_ON+T_REQ ;STOP OR OFF ACTIVE REQUEST?
	JZ	FRETP2 ;YES, FREE ACTIVE REQUEST COUNT
	STI
	RET
;RESET STOP ON TRAP
;
global RSTTRP
RSTTRP:	CLI
	MOV	AL,byte [BX]
	AND	AL,T_ON+T_REQ
	CMP	AL,byte [BX]
	MOV	byte [BX],AL
	JNZ	SETCHK ;IF NEW STATUS, CHECK FOR SETTRP
	STI
	RET
;
;REQUEST TRAP
;
global REQTRP
REQTRP:	CLI
	MOV	AL,byte [BX]
	AND	AL,T_ON
	JZ	REQTPX ;TRAP NOT ON
	MOV	AL,byte [BX]
	OR	AL,T_REQ
	CMP	AL,byte [BX]
	JZ	REQTPX ;NO CHANGE
	MOV	byte [BX],AL
SETCHK:	XOR	AL,T_ON+T_REQ
	JZ	SETTP2 ;GO SET TRAP GLOBAL FLAG
REQTPX:	STI
	RET
;SET TRAP GLOBAL FLAG
;
global SETTRP
SETTRP:	CLI
SETTP2:	MOV AL, byte [ONGSBF]
	INC	AL
	MOV byte [ONGSBF], AL
	STI
	RET
;FREE TRAP
;
global FRETRP
FRETRP:	CLI
	MOV	AL,byte [BX]
	AND	AL,T_ON+T_STOP
	CMP	AL,byte [BX]
	MOV	byte [BX],AL
	JNZ	FRETP2 ;DECR GLOBAL FLAG ALSO
FRETP1:	STI
	RET
FRETP2:	MOV AL, byte [ONGSBF]
	SUB	AL,1
	JB	FRETP1
extern ONGSBF
	MOV byte [ONGSBF], AL
	STI
	RET
;INITIALIZE TRAP TABLE
;
global INITRP
INITRP:
extern TRPTBL
	MOV	BX,TRPTBL ;HL=TRAP TABLE ADDRESS
	MOV	CH,NUMTRP ;B=NUMBER OF TRAPS
	XOR	AL,AL
INITP0:	MOV	byte [BX],AL ;TRAP OFF
	INC	BX
	MOV	byte [BX],AL
	INC	BX
	MOV	byte [BX],AL ;CLEAR GOSUB ADDR TOO!
	INC	BX
	DEC	CH
	JNZ	INITP0
	MOV byte [ONGSBF], AL
	RET
;GO TO TRAP IF ANY ENABLED AND REQUESTED
;
global GOTRP
GOTRP:
	MOV AL, byte [ONEFLG]
	OR	AL,AL
	JZ	$+3
	RET ;CAN'T TRAP FROM ERROR TRAP
	PUSH	BX ;SAVE TESXT POINTER
	MOV BX, [CURLIN]
	MOV	AL,BH
	AND	AL,BL
	INC	AL
	JZ	GOTRPX ;CAN'T TRAP FROM DIRECT STATEMENT
;CHECK FOR ENABLED REQUESTS
	MOV	BX,TRPTBL
	MOV	CH,NUMTRP ;HL=TRAP TABLE ADDRESS, B= # OF TRAPS
GOTRPL:	MOV	AL,byte [BX]
	CMP	AL,T_ON+T_REQ
	JZ	GOTRP2 ;ENABLED AND REQUESTED
GOTRP1:	LAHF
	INC	BX ;NEXT ENTRY
	SAHF
	LAHF
	INC	BX ;
	SAHF
	LAHF
	INC	BX ;
	SAHF
	DEC	CH
	JNZ	GOTRPL
GOTRPX:	POP	BX ;RESTORE TEXT POINTER
	RET
;
;TRAP REQUEST FOUND
;
GOTRP2:
	PUSH	CX ;SAVE STATE IN CASE ADDR IS ZERO
	LAHF
	INC	BX
	SAHF
	MOV	DL,byte [BX]
	LAHF
	INC	BX
	SAHF
	MOV	DH,byte [BX] ;DE=TRAP GOSUB ADDR
	LAHF
	DEC	BX
	SAHF
	LAHF
	DEC	BX ;HL:=TRAP FLAG
	SAHF
	MOV	AL,DH
	OR	AL,DL
	POP	CX ;RESTORE COUNTER
	JZ	GOTRP1 ;GOSUB ADDR NOT SPECIFIED,TRY NEXT RTRAP
	PUSH	DX ;PUT GOSUB ADDR ON STACK
	PUSH	BX ;PUT FLAG ADDR ON STACK
	CALL	FRETRP ;FREE TRAP REQUEST
	CALL	STPTRP ;PUT STOP ON TRAP
	MOV	CL,3
	CALL	GETSTK ;MAKE SURE ROOM IN STACK
	POP	CX ;BC=TRAP FLAG ADDRESS
	POP	DX ;DE=GOUSUB ROUTINE ADDR
	POP	BX ;REMOVE RETURN AND HL=TEXT POINTER
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI
	POP	BX
extern GOSUB2
	JMP	GOSUB2 ;GOSUB TO ADDR IN DE, FLAG ADDR IN BC
; AND TEXT PTR IN HL
; SUBTTL RESTORE, STOP, END
RESTORE:	XCHG	BX,DX ;SAVE [H,L] IN [D,E]
	MOV BX, [TXTTAB]
	JZ	BGNRST ;RESTORE DATA POINTER TO BEGINNING OF PROGRAM
	XCHG	BX,DX ;TEXT POINTER BACK TO [H,L]
	CALL	LINGET ;GET THE FOLLOWING LINE NUMBER
	PUSH	BX ;SAVE TEXT POINTER
	CALL	FNDLIN ;FIND THE LINE NUMBER
	MOV	BX,CX ;GET POINTER TO LINE IN [H,L]
	POP	DX ;TEXT POINTER BACK TO [D,E]
	JNAE	??L001
	JMP	USERR ;SHOULD HAVE FOUND LINE
??L001:
BGNRST:
	DEC	BX ;INITIALIZE DATPTR TO [TXTTAB]-1
RESFIN:	MOV [DATPTR], BX ;READ FINISHES COME TO RESFIN
	XCHG	BX,DX ;GET THE TEXT POINTER BACK
	RET
STOP:	JZ	$+3
	RET ;RETURN IF NOT CONTROL-C AND MAKE
;SURE "STOP" STATEMENTS HAVE A TERMINATOR
STOPRG:
%define HLPEDT PC8A
	INC	AL
	JMP	CONSTP
ENDST:	JZ	$+3
	RET ;MAKE SURE "END" STATEMENTS HAVE A TERMINATOR
	XOR	AL,AL ;clear ONEFLG to indicate that we aren't
	MOV byte [ONEFLG], AL ;within an error-trapping routine
ENDS1:
	PUSHF ;PRESERVE CONDITION CODES OVER CALL TO CLSALL
	JNZ	??L002
	CALL	CLSALL
??L002:
	POPF ;RESTORE CONDITION CODES
CONSTP:
	MOV [SAVTXT], BX ;SAVE FOR "CONTINUE"
	MOV	BX,TEMPST ;RESET STRING TEMP POINTER
	MOV [TEMPPT], BX ;SAVE IN CASE ^C PRINT USING
db 0o273 ; SKIP	;"LXI H," OVER NEXT TWO
STPEND:	OR	AL,0o377 ;SET NON-ZERO TO FORCE PRINTING OF BREAK MESSAGE
	POP	CX ;POP OFF NEWSTT ADDRESS
ENDCON:	MOV BX, [CURLIN] ;SAVE CURLIN
	PUSH	BX ;SAVE LINE TO PRINT
	PUSHF ;SAVE THE MESSAGE FLAG
;ZERO MEANS DON'T PRINT "BREAK"
	MOV	AL,BL
	AND	AL,BH ;SEE IF IT WAS DIRECT
	INC	AL
	JZ	DIRIS ;IF NOT SET UP FOR CONTINUE
	MOV [OLDLIN], BX ;SAVE OLD LINE #
	MOV BX, [SAVTXT] ;GET POINTER TO START OF STATEMENT
	MOV [OLDTXT], BX ;SAVE IT
DIRIS:
extern CNTOFL
	XOR	AL,AL
	MOV byte [CNTOFL], AL ;FORCE OUTPUT
extern FINLPT
	CALL	FINLPT
	CALL	CRDONZ ;PRINT CR IF TTYPOS .NE. 0
	POPF ;GET BACK ^C FLAG
	MOV	BX,BRKTXT ;"BREAK"
	JZ	??L003
	JMP	ERRFIN ;CALL STROUT AND FALL INTO READY
??L003:
	JMP	STPRDY ;POP OFF LINE NUMBER & FALL INTO READY
;PAGE
; SUBTTL CTRLPT, DDT, CONT, NULL, TRON, TROFF
global CTROPT
CTROPT:	MOV	AL,CONTO ;PRINT AN ^O.
global CTRLPT
CTRLPT:	PUSH	AX ;SAVE CURRENT CHAR
	SUB	AL,3 ;CONTROL-C?
	JNZ	NTCTCT ;NO
	MOV byte [CNTOFL], AL ;RESET ^O FLAG
NTCTCT:
	MOV	AL,"^" ;PRINT UP-ARROW.
	CALL	OUTDO ;SEND IT
	POP	AX ;GET BACK CONTROL CHAR.
	ADD	AL,0o100 ;MAKE PRINTABLE
	CALL	OUTDO ;SEND IT
	MOV	AL,0o377 ;MARK LINE AS NOT FOR INPUT
	CALL	OUTDO
	JMP	CRDO ;AND THEN SEND CRLF.
CONT:	MOV BX, [OLDTXT] ;A STORED TEXT POINTER OF
;ZERO IS SETUP BY STKINI
;AND INDICATES THERE IS NOTHING
;TO CONTINUE
	OR	BX,BX ;"STOP","END",TYPING CRLF
;TO "INPUT" AND ^C SETUP OLDTXT
RESERR:	MOV	DX,ERRC_ERRCN ;"CAN'T CONTINUE"
	JNZ	??L004
	JMP	ERROR
??L004:
	MOV DX, [OLDLIN]
	MOV [CURLIN], DX ;SET UP OLD LINE # AS CURRENT LINE #
	RET
extern NULCNT
global NULL
NULL:	CALL	GETBYT
	JZ	$+3
	RET ;MAKE SURE THERE IS A TERMINATOR
	INC	AL ;CODE AT CRDO EXPECTS AT LEAST 1
	MOV byte [NULCNT], AL ;CHANGE NUMBER OF NULLS
	RET
TON: db 0o270 ; SKIP	;"MVI A," NON-ZERO QUANTITY
TOFF:	XOR	AL,AL ;MAKE [A]=0 FOR NO TRACE
	MOV byte [TRCFLG], AL ;UPDATE THE TRACE FLAG
	RET
;PAGE
; SUBTTL SWAP, ERASE
extern SWPTMP
global SWAP
SWAP:	CALL	PTRGET ;[D,E]=POINTER AT VALUE #1
	PUSH	DX ;SAVE THE POINTER AT VALUE #1
	PUSH	BX ;SAVE THE TEXT POINTER
	MOV	BX,SWPTMP ;TEMPORARY STORE LOCATION
	CALL	VMOVE ;SWPTMP=VALUE #1
	MOV BX, [ARYTAB] ;GET ARYTAB SO CHANGE CAN BE NOTED
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;GET THE TEXT POINTER BACK
;AND SAVE CURRENT [ARYTAB]
	CALL	GETYPR
	PUSH	AX ;SAVE THE TYPE OF VALUE #1
	CALL	SYNCHR
db 44 ;MAKE SURE THE VARIABLES ARE
;DELIMITED BY A COMMA
	CALL	PTRGET ;[D,E]=POINTER AT VALUE #2
	POP	AX
	MOV	CH,AL ;[B]=TYPE OF VALUE #1
	CALL	GETYPR ;[A]=TYPE OF VALUE #2
	CMP	AL,CH ;MAKE SURE THEY ARE THE SAME
	JZ	??L005
	JMP	TMERR ;IF NOT, "TYPE MISMATCH" ERROR
??L005:
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;[H,L]=OLD [ARYTAB] SAVE THE TEXT POINTER
	XCHG	BX,DX ;[D,E]=OLD [ARYTAB]
	PUSH	BX ;SAVE THE POINTER AT VALUE #2
	MOV BX, [ARYTAB] ;GET NEW [ARYTAB]
	CMP	BX,DX
	JNZ	GFCERR ;IF ITS CHANGED, ERROR
	POP	DX ;[D,E]=POINTER AT VALUE #2
	POP	BX ;[H,L]=TEXT POINTER
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;SAVE THE TEXT POINTER ON THE STACK
;[H,L]=POINTER AT VALUE #1
	PUSH	DX ;SAVE THE POINTER AT VALUE #2
	CALL	VMOVE ;TRANSFER VALUE #2 INTO VALUE #1'S OLD
;POSITION
	POP	BX ;[H,L]=POINTER AT VALUE #2
	MOV	DX,SWPTMP ;LOCATION OF VALUE #1
	CALL	VMOVE ;TRANSFER SWPTMP=VALUE #1 INTO VALUE #2'S
;OLD POSITION
	POP	BX ;GET THE TEXT POINTER BACK
	RET
GFCERR:	JMP	FCERR ;GIVE A FUNCTION CALL ERROR
global ERASE
ERASE:
	MOV	AL,1
	MOV byte [SUBFLG], AL ;THAT THIS IS "ERASE" CALLING PTRGET
	CALL	PTRGET ;GO FIND OUT WHERE TO ERASE
	JNZ	GFCERR ;PTRGET DID NOT FIND VARIABLE!
	PUSH	BX ;SAVE THE TEXT POINTER
	MOV byte [SUBFLG], AL ;ZERO OUT SUBFLG TO RESET "ERASE" FLAG
	MOV	BH,CH ;[B,C]=START OF ARRAY TO ERASE
	MOV	BL,CL
	DEC	CX ;BACK UP TO THE FRONT
	DEC	CX ;NO VALUE TYPE WITHOUT LENGTH=2
	DEC	CX ;BACK UP ONE MORE
LPBKNM:	MOV	SI,CX
	MOV	AL,[SI] ;GET A CHARACTER. ONLY THE COUNT HAS HIGH BIT=0
	DEC	CX ;SO LOOP UNTIL WE SKIP OVER THE COUNT
	OR	AL,AL ;SKIP ALL THE EXTRA CHARACTERS
	JNS	??L006
	JMP	LPBKNM
??L006:
	DEC	CX
	DEC	CX
	ADD	BX,DX ;[H,L]=THE END OF THIS ARRAY ENTRY
	XCHG	BX,DX ;[D,E]=END OF THIS ARRAY
	MOV BX, [STREND] ;[H,L]=LAST LOCATION TO MOVE UP
ERSLOP:	CMP	BX,DX ;SEE IF THE LAST LOCATION IS GOING TO BE MOVED
	MOV	SI,DX
	MOV	AL,[SI] ;DO THE MOVE
	MOV	DI,CX
	STOSB
	LAHF
	INC	DX ;UPDATE THE POINTERS
	SAHF
	LAHF
	INC	CX
	SAHF
	JNZ	ERSLOP ;MOVE THE REST
	DEC	CX
	MOV	BX,CX ;SETUP THE NEW STORAGE END POINTER
	MOV [STREND], BX
	POP	BX ;GET BACK THE TEXT POINTER
	MOV	AL,byte [BX] ;SEE IF MORE ERASURES NEEDED
	CMP	AL,0o54 ;ADDITIONAL VARIABLES DELIMITED BY COMMA
	JZ	$+3
	RET ;ALL DONE IF NOT
	CALL	CHRGTR
	JMP	ERASE
CASDON:
global POPAHT
POPAHT:	POP	AX ; POP PSW
	XCHG	AL,AH
	SAHF
	POP	BX ;GET THE TEXT POINTER
	RET
;
;TEST FOR A LETTER / CARRY ON=NOT A LETTER
;                    CARRY OFF=A LETTER
;
ISLET:	MOV	AL,byte [BX]
ISLET2:	CMP	AL,"A"
	JNB	$+3
	RET ;IF LESS THAN "A", RETURN EARLY
	CMP	AL,"Z"+1
	CMC
	RET
;PAGE
; SUBTTL CLEAR
global CLEAR
GCLERC:	JMP	CLEARC ;IFE LABEL  GO TO CLEARC
;Syntax: CLEAR [[a][,b [,c]]]
;
; a is a relic of pre-fiveo memory management and is ignored
; b is the highest memory location available to BASIC-80
; b is the the number of bytes in the data segment for BASIC-86
; c is the number of bytes to be used as stack space by BASIC
;
CLEAR:
	LAHF ; PUSH PSW
	XCHG	AL,AH
	PUSH	AX
	XCHG	AL,AH
	XOR	AL,AL ;Since FILTAB is reset below,
	MOV byte [NLONLY], AL ; close all files - even file 0,
	CALL	CLSALL ; because of DYNAMIC FDB's
	POP	AX ; POP PSW
	XCHG	AL,AH
	SAHF
	JZ	GCLERC ;IF NO FORMULA JUST CLEAR
	CMP	AL,0o54 ;ALLOW NO STRING SPACE
	JZ	CSKPCM
	CALL	INTID2 ;Get Dummy Integer Parameter into [D,E]
	DEC	BX
	CALL	CHRGTR ;SEE IF ITS THE END
	JZ	GCLERC
CSKPCM:	CALL	SYNCHR
db 0o54
	JZ	GCLERC
	MOV DX, [TOPMEM] ;Use current top of memory as default
	CMP	AL,0o54
	JZ	CLEARS ;SHOULD FINISH THERE
	CALL	GETMPM ;GET MEMORY SIZE PARAMETER
	PUSH	BX ;save text pointer
extern MAXMEM
	MOV BX, [MAXMEM] ;[HL]=highest byte available to BASIC
	CMP	BX,DX
	JAE	??L007
	JMP	FCERR ;branch if user tried to get more
??L007:
	POP	BX ;restore text pointer
CLEARS:	DEC	BX ;BACK UP
	CALL	CHRGTR ;GET CHAR
	PUSH	DX ;SAVE NEW HIGH MEM
	JZ	CDFSTK ;USE SAME STACK SIZE
	CALL	SYNCHR
db 0o54
	JZ	CDFSTK
	CALL	GETMPM ;GET STACK SIZE PARAMETER
	DEC	BX
	CALL	CHRGTR
	JZ	??L008
	JMP	SNERR
??L008:
CLEART:	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;SAVE TEXT POINTER
	PUSH	BX ;SAVE CANDIDATE FOR TOPMEM
	MOV	BX,(2*NUMLEV)+20 ;CHECK STACK SIZE IS REASONABLE
	CMP	BX,DX
	JAE	GOMERR
	POP	BX ;[HL]=candidate for TOPMEM
	CALL	SUBDE ;DE=HL-DE=High Ram - Stack Size=new stack bottom
	JB	GOMERR ;WANTED MORE THAN TOTAL!
	PUSH	BX ;SAVE STACK BOTTOM
	MOV BX, [VARTAB] ;TOP LOCATION IN USE
	MOV	CX,20 ;LEAVE BREATHING ROOM
	ADD	BX,CX
	CMP	BX,DX ;ROOM?
	JAE	GOMERR ;NO, DON'T EVEN CLEAR
	XCHG	BX,DX ;NEW STACK BASE IN [H,L]
extern FILTAB
extern STKLOW
	MOV [STKLOW], BX ;set bottom of stack limit
	MOV [FILTAB], BX ;set FDB chain base (No files are open)
	DEC	BX
	MOV	byte [BX],0 ;set string terminator so VAL$ will always work
	DEC	BX
	MOV [MEMSIZ], BX ;SET UP NEW STACK BOTTOM
	POP	BX ;HL=Highest Ram available to BASIC
	MOV [TOPMEM], BX ;SAVE IT, IT MUST BE OK
	POP	BX ;REGAIN THE TEXT POINTER
	JMP	GCLERC ;GO CLEAR
GETMPM:	CALL	FRMQNT ;EVALUATE FORMULA
	OR	DX,DX ;Memory size =0?
	JNZ	??L009
	JMP	FCERR ;Yes, error
??L009:
	RET
GOMERR:	JMP	OMERR ;GIVE OM ERROR
;CLEAR Default Stack Size to current stack size
;
CDFSTK:
	MOV DX, [TOPMEM] ;FIGURE OUT CURRENT STACK SIZE
extern STKLOW
db 0o53
db 0o26
dw STKLOW ;SUB DX,STKLOW
	JMP	CLEART
; [D,E]=[H,L]-[D,E]
global SUBDE
SUBDE:
db 0o213, 0o303 ;MOV AX,BX
db 0o53, 0o302 ;SUB AX,DX
db 0o213, 0o320 ;MOV DX,AX
	RET
;PAGE
global ISFLIO
extern PTRFIL
ISFLIO:
	PUSH	BX ;SAVE [H,L]
	MOV BX, [PTRFIL] ;GET FILE POINTER
	OR	BX,BX ;NO ZERO?
	POP	BX ;RESTORE [H,L]
	RET
;EXTERNAL DECLARATIONS REQUIRED FOR LABELSTUFF
; INTERNAL DECLARATIONS REQUIRED
;
;ALL THIS STUFF HAS BEEN ADDED FOR LABELS
;IF LABELS ARE REQUIRED  LABEL SWITCH SHLOULD BE ON
;;;
;
;
;CHKLBL ROUTINE CHECKS WHETHER THE LABEL IS ALREADY PRESENT IN THE SYMBOL TABLE
;HL=POINTER TO LABEL
;B=LABEL LENGTH
;DE IS SET TO THE WORD WHICH CONTAINS THE POINTER TO THE STMNT IN CASE THERE IS MATCH
;Z IS SET INCASE MATCH
;HL AND B ARE PRESERVED
