; Auto-converted mechanically from ../gw-basic/biprtu.asm
; Edit the converter or the generated source deliberately; do not hand-wave syntax changes.

; [ This translation created 10-Feb-83 by Version 4.3 ]
; .RADIX  8
%include "dwoem.inc"
; TITLE   BIPRTU  BASIC Interpreter PRINT USING Driver/WHG
; .RADIX	10
%assign TRSHHC 0
%assign NECPPC 0
; SUBTTL  PRINT USING DRIVER
;
; COME HERE AFTER THE "USING" CLAUSE IN A PRINT STATEMENT
; IS RECOGNIZED. THE IDEA IS TO SCAN THE USING STRING UNTIL
; THE VALUE LIST IS EXHAUSTED, FINDING STRING AND NUMERIC
; FIELDS TO PRINT VALUES OUT OF THE LIST IN,
; AND JUST OUTPUTING ANY CHARACTERS THAT AREN'T PART OF
; A PRINT FIELD.
;
; Data segment externs
extern FACLO
extern USFLG
; Code segment ( terminated by END at bottom of file )
extern CHRGTR
extern SYNCHR
extern CHKSTR
extern CRDO
extern FCERR
extern FRETM2
extern FRMCHK
extern FRMEVL
extern OUTDO
extern PUFOUT
extern SNERR
extern STROUT
extern STRPRT
extern LEFTUS
global PRINUS
%define CSTRNG 0o134
%define CURNCY 0o44 ;USE DOLLAR SIGN AS DEFAULT
PRINUS:	CALL	FRMCHK ;EVALUATE THE "USING" STRING
	CALL	CHKSTR ;MAKE SURE IT IS A STRING
	CALL	SYNCHR
db 0o73 ;MUST BE DELIMITED BY A SEMI-COLON
	XCHG	BX,DX ;[D,E]=TEXT POINTER
	MOV BX, [FACLO] ;GET POINTER TO "USING" STRING DESCRIPTOR
	JMP	INIUS ;DONT POP OFF OR LOOK AT USFLG
REUSST:	MOV AL, byte [USFLG] ;DID WE PRINT OUT A VALUE LAST SCAN?
	OR	AL,AL ;SET CC'S
	JZ	FCERR3 ;NO, GIVE ERROR
	POP	DX ;[D,E]=POINTER TO "USING" STRING DESCRIPTOR
	XCHG	BX,DX ;[D,E]=TEXT POINTER
INIUS:	PUSH	BX ;SAVE THE POINTER TO "USING" STRING DESCRIPTOR
	XOR	AL,AL ;INITIALLY INDICATE THERE ARE MORE
;VALUES IN THE VALUE LIST
	MOV byte [USFLG], AL ;RESET THE FLAG THAT SAYS VALUES PRINTED
	INC	AL ;TURN THE ZERO FLAG OFF
;TO INDICATE THE VALUE LIST HASN'T ENDED
	PUSHF ;SAVE FLAG INDICATING WHETHER THE VALUE
;LIST HAS ENDED
	PUSH	DX ;SAVE THE TEXT POINTER INTO THE VALUE LIST
	MOV	CH,byte [BX] ;[B]=LENGTH OF THE "USING" STRING
	INC	CH ;Is the using string null?
	DEC	CH
FCERR3:	JNZ	??L000
	JMP	FCERR ;IF SO, "ILLEGAL FUNCTION CALL"
??L000:
	INC	BX ;[H,L]=POINTER AT THE "USING" STRING'S
	MOV	BX,[BX] ;DATA
	JMP	PRCCHR ;GO INTO THE LOOP TO SCAN
;THE "USING" STRING
;NECPPC does not have string formatter
; because of ROM space
BGSTRF:	MOV	DL,CH ;SAVE THE "USING" STRING CHARACTER COUNT
	PUSH	BX ;SAVE THE POINTER INTO THE "USING" STRING
	MOV	CL,2 ;THE \\ STRING FIELD HAS 2 PLUS
;NUMBER OF ENCLOSED SPACES WIDTH
LPSTRF:	MOV	AL,byte [BX] ;GET THE NEXT CHARACTER
	INC	BX ;ADVANCE THE POINTER AT THE "USING" STRING
;DATA
	CMP	AL,CSTRNG ;THE FIELD TERMINATOR?
	JNZ	??L001
	JMP	ISSTRF ;GO EVALUATE A STRING AND PRINT
??L001:
	CMP	AL," " ;A FIELD EXTENDER?
	JNZ	NOSTRF ;IF NOT, ITS NOT A STRING FIELD
	INC	CL ;INCREMENT THE FIELD WIDTH
;SEE IF THERE ARE MORE CHARACTERS
	DEC	CH
	JNZ	LPSTRF ;KEEP SCANNING FOR THE FIELD TERMINATOR
;
; SINCE  STRING FIELD WASN'T FOUND, THE "USING" STRING 
; CHARACTER COUNT AND THE POINTER INTO IT'S DATA MUST
; BE RESTORED AND THE "\" PRINTED
;
NOSTRF:	POP	BX ;RESTORE THE POINTER INTO "USING" STRING'S DATA
	MOV	CH,DL ;RESTORE THE "USING" STRING CHARACTER COUNT
	MOV	AL,CSTRNG ;RESTORE THE CHARACTER
;
; HERE TO PRINT THE CHARACTER IN [A] SINCE IT WASN'T PART OF ANY FIELD
;
NEWUCH:	CALL	PLSPRT ;IF A "+" CAME BEFORE THIS CHARACTER
;MAKE SURE IT GETS PRINTED
	CALL	OUTDO ;PRINT THE CHARACTER THAT WASN'T
;PART OF A FIELD
PRCCHR:	XOR	AL,AL ;SET [D,E]=0 SO IF WE DISPATCH
	MOV	DL,AL ;SOME FLAGS ARE ALREADY ZEROED
	MOV	DH,AL ;DON'T PRINT "+" TWICE
PLSFIN:	CALL	PLSPRT ;ALLOW FOR MULTIPLE PLUSES
;IN A ROW
	MOV	DH,AL ;SET "+" FLAG
	MOV	AL,byte [BX] ;GET A NEW CHARACTER
	INC	BX
	CMP	AL,"!" ;CHECK FOR A SINGLE CHARACTER
	JNZ	??L002
	JMP	SMSTRF ;STRING FIELD
??L002:
	CMP	AL,"#" ;CHECK FOR THE START OF A NUMERIC FIELD 
	JZ	NUMNUM ;GO SCAN IT
	CMP	AL,"&" ;SEE IF ITS A VARIABLE LENGTH STRING FIELD
	JNZ	??L003
	JMP	VARSTR ;GO PRINT ENTIRE STRING
??L003:
	DEC	CH ;ALL THE OTHER POSSIBILITIES
;REQUIRE AT LEAST 2 CHARACTERS
	JNZ	??L004
	JMP	REUSIN ;IF THE VALUE LIST IS NOT EXHAUSTED
??L004:
;GO REUSE "USING" STRING
	CMP	AL,"+" ;A LEADING "+" ?
	MOV	AL,8 ;SETUP [D] WITH THE PLUS-FLAG ON IN
	JZ	PLSFIN ;CASE A NUMERIC FIELD STARTS
	DEC	BX ;POINTER HAS ALREADY BEEN INCREMENTED
	MOV	AL,byte [BX] ;GET BACK THE CURRENT CHARACTER
	INC	BX ;REINCREMENT THE POINTER
	CMP	AL,"." ;NUMERIC FIELD WITH TRAILING DIGITS
	JZ	DOTNUM ;IF SO GO SCAN WITH [E]=
;NUMBER OF DIGITS BEFORE THE "."=0
	CMP	AL,"_" ;CHECK FOR LITERAL CHARACTER DECLARATION
	JNZ	??L005
	JMP	LITCHR
??L005:
	CMP	AL,CSTRNG ;CHECK FOR A BIG STRING FIELD STARTER
	JZ	BGSTRF ;GO SEE IF IT REALLY IS A STRING FIELD
	CMP	AL,byte [BX] ;SEE IF THE NEXT CHARACTER MATCHES THE
;CURRENT ONE
	JNZ	NEWUCH ;IF NOT, CAN'T HAVE $$ OR ** SO ALL THE
;POSSIBILITIES ARE EXHAUSTED
	CMP	AL,CURNCY ;IS IT $$ ?
	JZ	DOLRNM ;GO SET UP THE FLAG BIT
	CMP	AL,"*" ;IS IT ** ?
	JNZ	NEWUCH ;IF NOT, ITS NOT PART
;OF A FIELD SINCE ALL THE POSSIBILITIES
;HAVE BEEN TRIED
	INC	BX ;CHECK FOR $
	MOV	AL,CH ;SEE IF THE "USING" STRING IS LONG
	CMP	AL,2 ;ENOUGH FOR THE SPECIAL CASE OF
	JB	NOTSPC ; **$
	MOV	AL,byte [BX]
	CMP	AL,CURNCY ;IS THE NEXT CHARACTER $ ?
NOTSPC:	MOV	AL,32 ;SET THE ASTERISK BIT
	JNZ	SPCNUM ;IF IT NOT THE SPECIAL CASE, DON'T
;SET THE DOLLAR SIGN FLAG
	DEC	CH ;DECREMENT THE "USING" STRING CHARACTER COUNT
;TO TAKE THE $ INTO CONSIDERATION
	INC	DL ;INCREMENT THE FIELD WIDTH FOR THE
;FLOATING DOLLAR SIGN
db 0o276 ; SKIP	;"CPI" OVER THE NEXT BYTE
;MVI SI,  IN 8086
DOLRNM:	XOR	AL,AL ;CLEAR [A]
	ADD	AL,16 ;SET BIT FOR FLOATING DOLLAR SIGN FLAG
	INC	BX ;POINT BEYOND THE SPECIAL CHARACTERS
SPCNUM:	INC	DL ;SINCE TWO CHARACTERS SPECIFY
;THE FIELD SIZE, INITIALIZE [E]=1
	ADD	AL,DH ;PUT NEW FLAG BITS IN [A]
	MOV	DH,AL ;INTO [D]. THE PLUS FLAG MAY HAVE
;ALREADY BEEN SET
NUMNUM:	INC	DL ;INCREMENT THE NUMBER OF DIGITS BEFORE
;THE DECIMAL POINT
	MOV	CL,0 ;SET THE NUMBER OF DIGITS AFTER
;THE DECIMAL POINT = 0
	DEC	CH ;SEE IF THERE ARE MORE CHARACTERS
	JZ	ENDNUS ;IF NOT, WE ARE DONE SCANNING THIS
;NUMERIC FIELD
	MOV	AL,byte [BX] ;GET THE NEW CHARACTER
	INC	BX ;ADVANCE THE POINTER AT THE "USING" STRING DATA
	CMP	AL,"." ;DO WE HAVE TRAILING DIGITS?
	JZ	AFTDOT ;IF SO, USE SPECIAL SCAN LOOP
	CMP	AL,"#" ;MORE LEADING DIGITS ?
	JZ	NUMNUM ;INCREMENT THE COUNT AND KEEP SCANNING
	CMP	AL,0o54 ;DOES HE WANT A COMMA
;EVERY THREE DIGITS?
	JNZ	FINNUM ;NO MORE LEADING DIGITS, CHECK FOR ^^^
	MOV	AL,DH ;TURN ON THE COMMA BIT
	OR	AL,64
	MOV	DH,AL
	JMP	NUMNUM ;GO SCAN SOME MORE
;
; HERE WHEN A "." IS SEEN IN THE "USING" STRING
; IT STARTS A NUMERIC FIELD IF AND ONLY IF
; IT IS FOLLOWED BY A "#"
;
DOTNUM:	MOV	AL,byte [BX] ;GET THE CHARACTER THAT FOLLOWS
	CMP	AL,"#" ;IS THIS A NUMERIC FIELD?
	MOV	AL,"." ;IF NOT, GO BACK AND PRINT "."
	JZ	??L006
	JMP	NEWUCH
??L006:
	MOV	CL,1 ;INITIALIZE THE NUMBER OF
;DIGITS AFTER THE DECIMAL POINT
	INC	BX
AFTDOT:	INC	CL ;INCREMENT THE NUMBER OF DIGITS
;AFTER THE DECIMAL POINT
	DEC	CH ;SEE IF THE "USING" STRING HAS MORE
	JZ	ENDNUS ;CHARACTERS, AND IF NOT, STOP SCANNING
	MOV	AL,byte [BX] ;GET THE NEXT CHARACTER
	INC	BX
	CMP	AL,"#" ;MORE DIGITS AFTER THE DECIMAL POINT?
	JZ	AFTDOT ;IF SO, INCREMENT THE COUNT AND KEEP
;SCANNING
;
; CHECK FOR THE "^^^^" THAT INDICATES SCIENTIFIC NOTATION
;
FINNUM:	PUSH	DX ;SAVE [D]=FLAGS AND [E]=LEADING DIGITS
	MOV	DX,NOTSCI ;PLACE TO GO IF ITS NOT SCIENTIFIC
	PUSH	DX ;NOTATION
	MOV	DH,BH ;REMEMBER [H,L] IN CASE
	MOV	DL,BL ;ITS NOT SCIENTIFIC NOTATION
	CMP	AL,"^" ;IS THE FIRST CHARACTER "^" ?
	JZ	$+3
	RET
	CMP	AL,byte [BX] ;IS THE SECOND CHARACTER "^" ?
	JZ	$+3
	RET
	INC	BX
	CMP	AL,byte [BX] ;IS THE THIRD CHARACTER "^" ?
	JZ	$+3
	RET
	INC	BX
	CMP	AL,byte [BX] ;IS THE FOURTH CHARACTER "^" ?
	JZ	$+3
	RET
	INC	BX
	MOV	AL,CH ;WERE THERE ENOUGH CHARACTERS FOR "^^^^"
	SUB	AL,4 ;IT TAKES FOUR
	JNB	$+3
	RET
	POP	DX ;POP OFF THE NOTSCI RETURN ADDRESS
	POP	DX ;GET BACK [D]=FLAGS [E]=LEADING DIGITS
	MOV	CH,AL ;MAKE [B]=NEW CHARACTER COUNT
	INC	DH ;TURN ON THE SCIENTIFIC NOTATION FLAG
	INC	BX
	JMP	ENDNUS
NOTSCI:	XCHG	BX,DX ;RESTORE THE OLD [H,L]
	POP	DX ;GET BACK [D]=FLAGS [E]=LEADING DIGITS
ENDNUS:	MOV	AL,DH ;IF THE LEADING PLUS FLAG IS ON
	DEC	BX
	INC	DL ;INCLUDE LEADING "+" IN NUMBER OF DIGITS
	AND	AL,8 ;DON'T CHECK FOR A TRAILING SIGN
	JNZ	ENDNUM ;ALL DONE WITH THE FIELD IF SO
;IF THERE IS A LEADING PLUS
	DEC	DL ;NO LEADING PLUS SO DON'T INCREMENT THE
;NUMBER OF DIGITS BEFORE THE DECIMAL POINT
	MOV	AL,CH
	OR	AL,AL ;SEE IF THERE ARE MORE CHARACTERS
	JZ	ENDNUM ;IF NOT, STOP SCANNING
	MOV	AL,byte [BX] ;GET THE CURRENT CHARACTER
	SUB	AL,"-" ;TRAIL MINUS?
	JZ	SGNTRL ;SET THE TRAILING SIGN FLAG
	CMP	AL,"+"-"-" ;A TRAILING PLUS?
	JNZ	ENDNUM ;IF NOT, WE ARE DONE SCANNING
	MOV	AL,8 ;TURN ON THE POSITIVE="+" FLAG
SGNTRL:	ADD	AL,4 ;TURN ON THE TRAILING SIGN FLAG
	ADD	AL,DH ;INCLUDE WITH OLD FLAGS
	MOV	DH,AL
	DEC	CH ;DECREMENT THE "USING" STRING CHARACTER
;COUNT TO ACCOUNT FOR THE TRAILING SIGN
ENDNUM:	POP	BX ;[H,L]=THE OLD TEXT POINTER
	POPF ;POP OFF FLAG THAT SAYS WHETHER THERE
;ARE MORE VALUES IN THE VALUE LIST
	JZ	FLDFIN ;IF NOT, WE ARE DONE WITH THE "PRINT"
	PUSH	CX ;SAVE [B]=# OF CHARACTERS REMAINING IN
;"USING" STRING AND [C]=TRAILING DIGITS
	PUSH	DX ;SAVE [D]=FLAGS AND [E]=LEADING DIGITS
	CALL	FRMEVL ;READ A VALUE FROM THE VALUE LIST
	POP	DX ;[D]=FLAGS & [E]=# OF LEADING DIGITS
	POP	CX ;[B]=# CHARACTER LEFT IN "USING" STRING
;[C]=NUMBER OF TRAILING DIGITS
	PUSH	CX ;SAVE [B] FOR ENTERING SCAN AGAIN
	PUSH	BX ;SAVE THE TEXT POINTER
	MOV	CH,DL ;[B]=# OF LEADING DIGITS
	MOV	AL,CH ;MAKE SURE THE TOTAL NUMBER OF DIGITS
	ADD	AL,CL ;DOES NOT EXCEED TWENTY-FOUR
	CMP	AL,25
	JNAE	??L007
	JMP	FCERR ;IF SO, "ILLEGAL FUNCTION CALL"
??L007:
	MOV	AL,DH ;[A]=FLAG BITS
	OR	AL,128 ;TURN ON THE "USING" BIT
	CALL	PUFOUT ;PRINT THE VALUE
extern DSOUT
	CALL	DSOUT ;PRINT FROM THE DATA SEGMENT
FNSTRF:	POP	BX ;GET BACK THE TEXT POINTER
	DEC	BX ;SEE WHAT THE TERMINATOR WAS
	CALL	CHRGTR
	STC ;SET FLAG THAT CRLF IS DESIRED
	JZ	CRDNUS ;IF IT WAS A END-OF-STATEMENT
;FLAG THAT THE VALUE LIST ENDED
;AND THAT  CRLF SHOULD BE PRINTED
	MOV byte [USFLG], AL ;FLAG THAT VALUE HAS BEEN PRINTED.
;DOESNT MATTER IF ZERO SET, [A]
;MUST BE NON-ZERO OTHERWISE
	CMP	AL,0o73 ;A SEMI-COLON?
	JZ	SEMUSN ;A LEGAL DELIMITER
	CMP	AL,0o54 ;A COMMA ?
	JZ	??L008
	JMP	SNERR ;THE DELIMETER WAS ILLEGAL
??L008:
SEMUSN:	CALL	CHRGTR ;IS THERE ANOTHER VALUE?
CRDNUS:	POP	CX ;[B]=CHARACTERS REMAINING IN "USING" STRING
	XCHG	BX,DX ;[D,E]=TEXT POINTER
	POP	BX ;[H,L]=POINT AT THE "USING" STRING
	PUSH	BX ;DESCRIPTOR. RESAVE IT.
	PUSHF ;SAVE THE FLAG THAT INDICATES
;WHETHER OR NOT THE VALUE LIST TERMINATED
	PUSH	DX ;SAVE THE TEXT POINTER
;
; SINCE FRMEVL MAY HAVE FORCED GARBAGE COLLECTION
; WE HAVE TO USE THE NUMBER OF CHARACTERS ALREADY SCANNED
; AS AN OFFSET TO THE POINTER TO THE "USING" STRING'S DATA
; TO GET A NEW POINTER TO THE REST OF THE CHARACTERS TO
; BE SCANNED
;
	MOV	AL,byte [BX] ;GET THE "USING" STRING'S LENGTH
	SUB	AL,CH ;SUBTRACT THE NUMBER OF CHARACTERS
;ALREADY SCANNED
	INC	BX ;[H,L]=POINTER AT
	MOV	DH,0 ;SETUP [D,E] AS A DOUBLE BYTE OFFSET
	MOV	DL,AL
	MOV	BX,[BX] ;THE "USING" STRING'S STRING DATA
	ADD	BX,DX ;ADD ON THE OFFSET TO GET
;THE NEW POINTER
CHKUSI:	MOV	AL,CH ;[A]=THE NUMBER OF CHARACTERS LEFT TO SCAN
	OR	AL,AL ;SEE IF THERE ARE ANY LEFT
	JZ	??L009
	JMP	PRCCHR ;IF SO, KEEP SCANNING
??L009:
	JMP	FINUSI ;SEE IF THERE ARE MORE VALUES
REUSIN:	CALL	PLSPRT ;PRINT A "+" IF NECESSARY
	CALL	OUTDO ;PRINT THE FINAL CHARACTER
FINUSI:	POP	BX ;POP OFF THE TEXT POINTER
	POPF ;POP OFF THE INDICATOR OF WHETHER OR NOT
;THE VALUE LIST HAS ENDED
	JZ	??L010
	JMP	REUSST ;IF NOT, REUSE THE "USING" STRING
??L010:
FLDFIN:	JNB	??L011
	CALL	CRDO ;IF NOT COMMA OR SEMI-COLON
??L011:
;ENDED THE VALUE LIST
;PRINT A CRLF
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;SAVE THE TEXT POINTER
;[H,L]=POINT AT THE "USING" STRING'S
;DESCRIPTOR
	CALL	FRETM2 ;FINALLY FREE IT UP
	POP	BX ;GET BACK THE TEXT POINTER
extern FINPRT
	JMP	FINPRT ;ZERO [PTRFIL]
;
; HERE TO HANDLE A LITERAL CHARACTER IN THE USING STRING PRECEDED
; BY "_"
;
LITCHR:	CALL	PLSPRT ;PRINT PREVIOUS "+" IF ANY
	DEC	CH ;DECREMENT COUNT FOR ACTUAL CHARACTER
	MOV	AL,byte [BX] ;FETCH LITERAL CHARACTER
	INC	BX
	CALL	OUTDO
	JMP	CHKUSI ;GO SEE IF USING STRING ENDED
;
; HERE TO HANDLE VARIABLE LENGTH STRING FIELD SPECIFIED WITH "&"
;
VARSTR:	MOV	CL,0 ;SET LENGTH TO 0 TO FLAG VARIABLE LENGTH
	JMP	ISSTR1
;NECPPC does not have string formatter
; because of ROM space
;
; HERE WHEN THE "!" INDICATING A SINGLE CHARACTER
; STRING FIELD HAS BEEN SCANNED
;
SMSTRF:	MOV	CL,1 ;SET THE FIELD WIDTH TO 1
	JMP	ISSTR1
ISSTRF:	POP	AX ;GET RID OF THE [H,L] THAT WAS BEING
;SAVED IN CASE THIS WASN'T A STRING FIELD
ISSTR1:	DEC	CH ;DECREMENT THE "USING" STRING CHARACTER COUNT
	CALL	PLSPRT ;PRINT A "+" IF ONE CAME BEFORE THE FIELD
	POP	BX ;TAKE OFF THE TEXT POINTER
	POPF ;TAKE OF THE FLAG WHICH SAYS
;WHETHER THERE ARE MORE VALUES IN THE
;VALUE LIST
	JZ	FLDFIN ;IF THERE ARE NO MORE VALUES
;THEN WE ARE DONE
	PUSH	CX ;SAVE [B]=NUMBER OF CHARACTERS YET TO
;BE SCANNED IN "USING" STRING
	CALL	FRMEVL ;READ A VALUE
	CALL	CHKSTR ;MAKE SURE ITS A STRING
	POP	CX ;[C]=FIELD WIDTH
	PUSH	CX ;RESAVE [B]
	PUSH	BX ;SAVE THE TEXT POINTER
	MOV BX, [FACLO] ;GET A POINTER TO THE DESCRIPTOR
	MOV	CH,CL ;[B]=FIELD WIDTH
	MOV	CL,0 ;SET UP FOR "LEFT$"
	MOV	AL,CH ;GET FIELD WITH IN [A]
	PUSH	AX ;SAVE THE FIELD WIDTH FOR SPACE PADDING
	MOV	AL,CH ;SEE IF VARIABLE LENGTH FIELD
	OR	AL,AL
	JZ	??L012
	CALL	LEFTUS
??L012:
	CALL	STRPRT ;PRINT THE STRING
	MOV BX, [FACLO] ;SEE IF IT NEEDS TO BE PADDED
	POP	AX ;[A]=FIELD WIDTH
	OR	AL,AL ;IF FIELD LENGTH IS 0 MUST BE "&" SO
	JNZ	??L013
	JMP	FNSTRF ;DONT PRINT ANY TRAILING SPACES
??L013:
	SUB	AL,byte [BX] ;[A]=AMOUNT OF PADDING NEEDED
	MOV	CH,AL
	MOV	AL," " ;SETUP THE PRINT CHARACTER
	INC	CH ;DUMMY INCREMENT OF NUMBER OF SPACES
UPRTSP:	DEC	CH ;SEE IF MORE SPACES
	JNZ	??L014
	JMP	FNSTRF ;NO, GO SEE IF THE VALUE LIST ENDED AND
??L014:
;RESUME SCANNING
	CALL	OUTDO ;PRINT A SPACE
	JMP	UPRTSP ;AND LOOP PRINTING THEM
;
; WHEN A "+" IS DETECTED IN THE "USING" STRING
; IF A NUMERIC FIELD FOLLOWS A BIT IN [D] SHOULD
; BE SET, OTHERWISE "+" SHOULD BE PRINTED.
; SINCE DECIDING WHETHER A NUMERIC FIELD FOLLOWS IS VERY
; DIFFICULT, THE BIT IS ALWAYS SET IN [D].
; AT THE POINT IT IS DECIDED A CHARACTER IS NOT PART
; OF A NUMERIC FIELD, THIS ROUTINE IS CALLED TO SEE
; IF THE BIT IN [D] IS SET, WHICH MEANS
; A PLUS PRECEDED THE CHARACTER AND SHOULD BE
; PRINTED.
;
PLSPRT:	PUSH	AX ;SAVE THE CURRENT CHARACTER
	MOV	AL,DH ;CHECK THE PLUS BIT
	OR	AL,AL ;SINCE IT IS THE ONLY THING THAT COULD
;BE TURNED ON
	MOV	AL,"+" ;SETUP TO PRINT THE PLUS
	JZ	??L015
	CALL	OUTDO ;PRINT IT IF THE BIT WAS SET
??L015:
	POP	AX ;GET BACK THE CURRENT CHARACTER
	RET
