; Auto-converted mechanically from ../gw-basic/gweval.asm
; Edit the converter or the generated source deliberately; do not hand-wave syntax changes.

; [ This translation created 10-Feb-83 by Version 4.3 ]
; .RADIX  8
%include "dwoem.inc"
; TITLE   GWEVAL Copied from BINTRP.MAC
; .RADIX	10
%assign FETOK 0 ;For FE extended tokens
%assign FDTOK 0 ;For FD tokens too.  (Must have
;FETOK==1.)
;tokens.
%assign INTDEX 0 ;For Intelledex version.
%assign NMPAGE 1 ;Number of text pages (for GW
;Multi-page)
;KPOS, etc.
%assign LNREAD 0 ;For LINE READ statement
%assign MELCO 0 ;Mitsubishi Electronics Co.
%assign SIRIUS 0
%assign MCI 0
%assign ZENITH 0 ;ZENITH 8086
%assign TETRA 0
%assign CPM86 0
%assign HAL 0
%assign GENFLS 0
%assign PANDBL 0
%assign TSHIBA 0
%assign SGS 0
%assign ALPS 0
%assign ALPCPM 0
%assign GENWID 0
%assign NNECBS 0
%assign CAN8 0
%assign PC8A 0
%assign FN2SW 0 ;IBMTOK versions dispatch from IBMRES.MAC
%define LABEL PC8A
%define HLPEDT PC8A
%assign OKI 0
%assign BUBL 0
%assign NORNF 0
%assign IEESLV 0
%assign TRSHHC 0
%assign OLVPPC 0
%assign NECPPC 0
%assign USA 0 ;For HHC-USA version
%assign EUROPE 0 ;For HHC-EUROPE version
;Local Switches
;
%define LTRACE ALPCPM ;trace output selectable
%define LABEL PC8A
%define HLPEDT PC8A
%define UCEMSG NNECBS ;Upper case error messages.
%define OLD86 MELCO & CPM86 ;For "old" 8086 error messages (prior
;to alignment for IBM compatibility).
%define OLDBLD ALPCPM | ALPS | OKI | HAL | PC8A | BUBL | GW | TSHIBA
%include "gio86u.inc"
%include "msdosu.inc" ;MSDOS constants
extern INIT
extern SETGSB
extern ONGSBF
%assign BUFOFS 0
%assign BUFOFS 2 ;MUST CRUNCH INTO ERALIER PLACE FOR
; SINGLE QUOTE
%define KBFLEN BUFLEN+(BUFLEN/4) ;MAKE KRUNCH BUFFER SOMEWHAT
; LARGER THAN SOURCE BUFFER (BUF)
extern NAME
extern INLIN
extern CRDO
extern CRDONZ
extern STRCMP
extern FININL
extern PPSWRT
extern OUTDO
extern BLTU
extern CLEARC
extern GTMPRT
extern ISLET
extern ISLET2
extern PTRGET
extern QINLIN
extern SCRTCH
extern STKINI
extern RUNC
extern RESFIN
extern PTRGT2
extern STPEND
extern DIM
extern DCOMPR
extern SYNCHR
extern SIGN
extern PRGFIN
extern FILIND
extern FILINP
extern CLSALL
extern INDSKC
extern LRUN
extern FILGET
extern INXHRT
extern SGN
extern ABSFN
extern SQR
extern FDIV
extern FSUB
extern FMULT
extern RND ;MATHPK INTERNALS
extern ZERO
extern MOVE
extern FOUT
extern FIN
extern FCOMP
extern FADD
extern PUSHF
extern INT
extern MOVFR
extern MOVRF
extern MOVRM
extern INPRT
extern LINPRT
extern FDIVT
extern MOVFM
extern MOVMF
extern FADDS
extern INRART
extern NEG
extern BSERR
extern CAT
extern FREFAC
extern FRESTR
extern FRETMP
extern FRETMS
extern STRCPY
extern GETSTK
extern STRLIT
extern STRLT2
extern STRLT3
extern STRLTI
extern STROUT
extern STRPRT
extern STROUI
extern GETSPA
extern PUTNEW
extern STOP
extern OMERR
extern REASON
extern GARBA2 ;We have our own G. C.
extern INSTR
extern PRINUS
extern PUTTMP
extern FOUTH
extern FOUTO
extern STRO$
extern STRH$
extern STRNG$
extern TON
extern TOFF
extern SPACE$
extern SIGNS
extern UMULT
extern SIGNC
extern POPHRT
extern FINLPT
extern CONSIH
extern VMOVFA
extern VMOVAF
extern ISIGN
extern CONIA
extern VSIGN
extern VDFACS
extern VMOVMF
extern VMOVFM
extern FRCINT
extern FRCSNG
extern FRCDBL
extern VNEG
extern PUFOUT
extern DCXBRT
extern IADD
extern ISUB
extern IMULT
extern ICOMP
extern INEG
extern DADD
extern DSUB
extern DMULT
extern DDIV
extern DCOMP
extern VINT
extern FINDBL
extern INEG2
extern IDIV
extern IMOD
extern VMOVE
extern VALINT
extern VALSNG
extern FRCSTR
extern CHKSTR
extern MAKINT
extern MOVE1
extern SCNSEM
extern WHILE
extern WEND
extern CALLS
extern PROCHK
;The following block of externals was added on Dec 19, 1982 when BINTRP was
; Split up after the freeze of GW-BASIC Version 1.0
; This Split-up was not reflected in the PS1:<BASIC>BINTRP.MAC source.
; See Tom Corbett if you have any questions.
;
extern MEMSIZ
extern FRETOP
extern VARTAB
extern STREND
extern TXTTAB
extern ARYTAB
extern CURLIN
extern DOT
extern DATLIN
extern NLONLY
extern ERRLIN
extern ERRTXT
extern MRGFLG
extern CHNFLG
extern SAVSTK
extern SAVTXT
extern OLDLIN
extern NXTLIN
extern OLDTXT
extern ONELIN
extern ONEFLG
extern CNTOFL
extern TRCFLG
extern CONSAV
extern CONTXT
extern CONTYP
extern NUMCON
extern CONLO
extern AUTFLG
extern AUTLIN
extern AUTINC
extern KBUF
extern BUFMIN
extern BUF
extern PTRFIL
extern PTRFLG
extern DORES
extern VALTYP
extern FACLO
extern DFACLO
extern FAC
extern TEMP
extern TEMP2
extern TEMP3
extern TEMPA
extern DSCTMP
extern TEMPST
extern OPRTYP
extern SUBFLG
extern FVALSV
extern DEFTBL
extern FLGINP
extern FLGSCN
extern OVCSTR
extern INPPAS
extern USRTAB
extern DONUM
extern ENDPRG
extern ENDFOR
extern DATPTR
extern FLGOVC
extern ERRFLG
extern SAVSEG
extern PRMLN2
extern PARM2
extern PRMLEN
extern PRMSTK
extern PARM1
extern FUNACT
extern NOFUNS
extern OPTVAL
extern OPTFLG
extern RNDX
extern OPTAB
extern OPCNT
extern INTDSP
extern SNGDSP
extern DBLDSP
extern FRCTBL
extern DOL_OVMSG
extern ERRTAB
extern REDDY
extern ERRFAO
extern ERRFAE
;ERRUE+DSKERR-NONDSK
;DSKERR-NONDSK
;The following externs are defined in GWMAIN.MAC
;
extern TMERR
extern SNERR
extern CHRGTR
extern MOERR
extern OVERR
extern FCERR
extern ERROR
extern CONFAC
extern FRMQNT
extern DATA
extern LETCN4
extern DOL_STPRN
extern FRQINT
extern LINGET
extern UFERR
;
; The reserved word tables are in another module.  Consequently
; many things must be declared external.  All of these things
; are in the code segement or are absolutes (like tokens).
; I.e., they are not in the data segment.
;
extern FUNDSP
;
; Since the dispatch table is also no longer in BINTRP many
; addresses need to be declared internal.
;
global DEF
global FNINP
global FNOUT
global FNWAIT
global LABBCK
; SUBTTL FORMULA EVALUATION CODE
;
; THE FORMULA EVALUATOR STARTS WITH
; [H,L] POINTING TO THE FIRST CHARACTER OF THE FORMULA.
; AT THE END [H,L] POINTS TO THE TERMINATOR.
; THE RESULT IS LEFT IN THE FAC.
; ON RETURN [A] DOES NOT REFLECT THE TERMINATING CHARACTER
;
; THE FORMULA EVALUATOR USES THE OPERATOR TABLE (OPTAB)
; TO DETERMINE PRECEDENCE AND DISPATCH ADDRESSES FOR
; EACH OPERATOR.
; A TEMPORARY RESULT ON THE STACK HAS THE FOLLOWING FORMAT
;
; THE ADDRESS OF 'RETAOP' -- THE PLACE TO RETURN ON COMPLETION
; OF OPERATOR APPLICATION
;
; THE FLOATING POINT TEMPORARY RESULT
;
; THE ADDRESS OF THE OPERATOR ROUNTINE
;
; THE PRECEDENCE OF THE OPERATOR
;
; TOTAL 10 BYTES
;
global FRMEQL
FRMEQL:	CALL	SYNCHR
db EQULTK ;CHECK FOR EQUAL SIGN
	JMP	FRMEVL
global FRMPRN
FRMPRN:	CALL	SYNCHR
db "(" ;GET PAREN BEFORE FORMULA
global FRMEVL
FRMEVL:	DEC	BX ;BACK UP CHARACTER POINTER
global FRMCHK
FRMCHK:	MOV	DH,0 ;INITIAL DUMMY PRECEDENCE IS 0
LPOPER:	PUSH	DX ;SAVE PRECEDENCE
	MOV	CL,1 ;EXTRA SPACE NEEDED FOR RETURN ADDRESS
	CALL	GETSTK ;MAKE SURE THERE IS ROOM FOR RECURSIVE CALLS
	CALL	EVAL ;EVALUATE SOMETHING
;RESET OVERFLOW PRINTING BACK TO NORMAL
	XOR	AL,AL ;(SET TO 1 AT FUNDSP TO SUPPRESS
	MOV byte [FLGOVC], AL ;MULTIPLE OVERFLOW MESSAGES)
global TSTOP
TSTOP:	MOV [TEMP2], BX ;SAVE TEXT POINTER
RETAOP:	MOV BX, [TEMP2] ;RESTORE TEXT PTR
	POP	CX ;POP OFF THE PRECEDENCE OF OLDOP
NOTSTV:	MOV	AL,byte [BX] ;GET NEXT CHARACTER
	MOV [TEMP3], BX ;SAVE UPDATED CHARACTER POINTER
	CMP	AL,GREATK ;IS IT AN OPERATOR?
	JNB	$+3
	RET ;NO, ALL DONE (THIS CAN RESULT IN OPERATOR
;APPLICATION OR ACTUAL RETURN)
	CMP	AL,LESSTK+1 ;SOME KIND OF RELATIONAL?
	JB	DORELS ;YES, DO IT
	SUB	AL,PLUSTK ;SUBTRACT OFFSET FOR FIRST ARITHMETIC
	MOV	DL,AL ;MUST MULTIPLY BY 3 SINCE
;OPTAB ENTRIES ARE 3 LONG
	JNZ	NTPLUS ;NOT ADDITION OP
	MOV AL, byte [VALTYP] ;SEE IF LEFT PART IS STRING
	CMP	AL,3 ;SEE IF ITS A STRING
	MOV	AL,DL ;REFETCH OP-VALUE
	JNZ	??L000
	JMP	CAT ;MUST BE CAT
??L000:
NTPLUS:
	CMP	AL,LSTOPK ;HIGHER THAN THE LAST OP?
	JNAE	$+3
	RET ;YES, MUST BE TERMINATOR
	MOV	BX,OPTAB ;CREATE INDEX INTO OPTAB
	MOV	DH,0 ;MAKE HIGH BYTE OF OFFSET=0
	ADD	BX,DX ;ADD IN CALCULATED OFFSET
	MOV	AL,CH ;[A] GETS OLD PRECEDENCE
db 0o56 ;CODE SEGMENT FETCH
	MOV	DH,byte [BX] ;REMEMBER NEW PRECEDENCE
	CMP	AL,DH ;OLD-NEW
	JNAE	$+3
	RET ;MUST APPLY OLD OP
;IF HAS GREATER OR = PRECEDENCE
;NEW OPERATOR
	PUSH	CX ;SAVE THE OLD PRECEDENCE
	MOV	CX,RETAOP ;PUT ON THE ADDRESS OF THE
	PUSH	CX ;PLACE TO RETURN TO AFTER OPERATOR APPLICATION
	MOV	AL,DH ;SEE IF THE OPERATOR IS EXPONENTIATION
	CMP	AL,127 ;WHICH HAS PRECEDENCE 127
	JZ	EXPSTK ;IF SO, "FRCSNG" AND MAKE A SPECIAL STACK ENTRY
	CMP	AL,81 ;SEE IF THE OPERATOR IS "AND" OR "OR"
	JB	ANDORD ;AND IF SO "FRCINT" AND
;MAKE A SPECIAL STACK ENTRY
	AND	AL,254 ;MAKE 123 AND 122 BOTH MAP TO 122
	CMP	AL,122 ;MAKE A SPECIAL CHECK FOR "MOD" AND "IDIV"
	JZ	ANDORD ;IF SO, COERCE ARGUMENTS TO INTEGER
; THIS CODE PUSHES THE CURRENT VALUE IN THE FAC
; ONTO THE STACK, EXCEPT IN THE CASE OF STRINGS IN WHICH IT CALLS
; TYPE MISMATCH ERROR. [D] AND [E] ARE PRESERVED.
;
NUMREL:
	MOV AL, byte [VALTYP] ;FIND OUT WHAT TYPE OF VALUE WE ARE SAVING
	SUB	AL,3 ;SETUP THE CONDITION CODES
;SET ZERO FOR STRINGS
	JNZ	??L001
	JMP	TMERR
??L001:
db 0o377
db 0o66
dw FACLO ;PUSH FACLO
	JNS	??L002
	JMP	VPUSHD ;ALL DONE IF THE DATA WAS AN INTEGER
??L002:
db 0o377
db 0o66
dw FACLO+2 ;PUSH FAC-1,0 ON THE STACK
	JP	??L003
	JMP	VPUSHD ;ALL DONE IF WE HAD A SNG
??L003:
db 0o377
db 0o66
dw DFACLO ;PUSH ON LOW BYTES OF DP FAC
db 0o377
db 0o66
dw DFACLO+2 ;PUSH ON NEXT TWO BYES OF DP FAC
VPUSHD:
	ADD	AL,3 ;FIX [A] TO BE THE VALTYP OF THE NUMBER
;JUST PUSHED ON THE STACK
	MOV	CL,DL ;[C]=OPERATOR NUMBER
	MOV	CH,AL ;[B]=TYPE OF VALUE ON THE STACK
	PUSH	CX ;SAVE THESE THINGS FOR APPLOP
	MOV	CX,APPLOP ;GENERAL OPERATOR APPLICATION
;ROUTINE -- DOES TYPE CONVERSIONS
FINTMP:	PUSH	CX ;SAVE PLACE TO GO
	MOV BX, [TEMP3] ;REGET THE TEXT POINTER
	JMP	LPOPER
DORELS:	MOV	DH,0 ;ASSUME NO RELATION OPS
;ALSO SETUP THE HIGH ORDER OF THE INDEX INTO OPTAB
LOPREL:	SUB	AL,GREATK ;IS THIS ONE RELATION?
	JB	FINREL ;RELATIONS ALL THROUGH
	CMP	AL,NMREL ;IS IT REALLY RELATIONAL?
	JAE	FINREL ;NO JUST BIG
	CMP	AL,1 ;SET UP BITS BY MAPPING
	RCL	AL,1 ;0 TO 1 1 TO 2 AND 2 TO 4
	XOR	AL,DH ;BRING IN THE OLD BITS
	CMP	AL,DH ;MAKE SURE RESULT IS BIGGER
	MOV	DH,AL ;SAVE THE MASK
	JAE	??L004
	JMP	SNERR ;DON'T ALLOW TWO OF THE SAME
??L004:
	MOV [TEMP3], BX ;SAVE CHARACTER POINTER
	CALL	CHRGTR ;GET THE NEXT CANDIDATE
	JMP	LOPREL
;
; FOR EXPONENTIATION WE WANT TO FORCE THE CURRENT VALUE IN THE FAC
; TO BE SINGLE PRECISION. WHEN APPLICATION TIME COMES WE FORCE
; THE RIGHT HAND OPERAND TO SINGLE PRECISION AS WELL
;
extern FPWRQ
EXPSTK:	CALL	FRCSNG ;COERCE LEFT HAND OPERAND
	CALL	PUSHF ;PUT IT ON THE STACK
	MOV	CX,FPWRQ ;PLACE TO COERCE RIGHT HAND
;OPERAND AND DO EXPONENTIATION
	MOV	DH,127 ;RESTORE THE PRECEDENCE
	JMP	FINTMP ;FINISH ENTRY AND EVALUATE MORE FORMULA
;
; FOR "AND" AND "OR" AND "\" AND "MOD" WE WANT TO FORCE THE CURRENT VALUE
; IN THE FAC TO BE AN INTEGER, AND AT APPLICATION TIME FORCE THE RIGHT
; HAND OPERAND TO BE AN INTEGER
;
ANDORD:	PUSH	DX ;SAVE THE PRECEDENCE
	CALL	FRCINT
	POP	DX ;[D]=PRECEDENCE
	PUSH	BX ;PUSH THE LEFT HAND OPERAND
	MOV	CX,DANDOR ;"AND" AND "OR" DOER
	JMP	FINTMP ;PUSH ON THIS ADDRESS,PRECEDENCE
;AND CONTINUE EVALUATION
;
; HERE TO BUILD AN ENTRY FOR A RELATIONAL OPERATOR
; STRINGS ARE TREATED SPECIALLY. NUMERIC COMPARES ARE DIFFERENT
; FROM MOST OPERATOR ENTRIES ONLY IN THE FACT THAT AT THE
; BOTTOM INSTEAD OF HAVING RETAOP, DOCMP AND THE RELATIONAL
; BITS ARE STORED. STRINGS HAVE STRCMP,THE POINTER AT THE STRING DESCRIPTOR,
; DOCMP AND THE RELATIONAL BITS.
;
FINREL:	MOV	AL,CH ;[A]=OLD PRECEDENCE
	CMP	AL,100 ;RELATIONALS HAVE PRECEDENCE 100
	JNAE	$+3
	RET ;APPLY EARLIER OPERATOR IF IT HAS
;HIGHER PRECEDENCE
	PUSH	CX ;SAVE THE OLD PRECEDENCE
	PUSH	DX ;SAVE [D]=RELATIONAL BITS
	MOV	DX,256*100+OPCNT ;[D]=PRECEDENCE=100
;[E]=DISPATCH OFFSET FOR
;COMPARES IN APPLOP=4
;IN CASE THIS IS A NUMERIC COMPARE
	MOV	BX,DOCMP ;ROUTINE TO TAKE COMPARE ROUTINE RESULT
;AND RELATIONAL BITS AND RETURN THE ANSWER
	PUSH	BX ;DOES A JMP TO RETAOP WHEN DONE
	CALL	GETYPR ;SEE IF WE HAVE A NUMERIC COMPARE
	JZ	??L005
	JMP	NUMREL ;YES, BUILD AN APPLOP ENTRY
??L005:
	MOV BX, [FACLO] ;GET THE POINTER AT THE STRING DESCRIPTOR
	PUSH	BX ;SAVE IT FOR STRCMP
	MOV	CX,STRCMP ;STRING COMPARE ROUTINE
	JMP	FINTMP ;PUSH THE ADDRESS, REGET THE TEXT POINTER
;SAVE THE PRECEDENCE AND SCAN
;MORE OF THE FORMULA
;
; APPLOP IS RETURNED TO WHEN IT IS TIME TO APPLY AN ARITHMETIC
; OR NUMERIC COMPARISON OPERATION.
; THE STACK HAS A DOUBLE BYTE ENTRY WITH THE OPERATOR
; NUMBER AND THE VALTYP OF THE VALUE ON THE STACK.
; APPLOP DECIDES WHAT VALUE LEVEL THE OPERATION
; WILL OCCUR AT, AND CONVERTS THE ARGUMENTS. APPLOP
; USES DIFFERENT CALLING CONVENTIONS FOR EACH VALUE TYPE.
; INTEGERS: LEFT IN [D,E] RIGHT IN [H,L]
; SINGLES:  LEFT IN [B,C,D,E] RIGHT IN THE FAC
; DOUBLES:  LEFT IN FAC   RIGHT IN ARG
;
APPLOP:	POP	CX ;[B]=STACK OPERAND VALUE TYPE
;[C]=OPERATOR OFFSET
	MOV	AL,CL ;SAVE IN MEMORY SINCE THE STACK WILL BE BUSY
	MOV byte [OPRTYP], AL ;A RAM LOCATION
	MOV AL, byte [VALTYP] ;GET VALTYP OF FAC
	CMP	AL,CH ;ARE VALTYPES THE SAME?
	JNZ	VALNSM ;NO
	CMP	AL,2 ;INTEGER?
	JZ	INTDPC ;YES, DISPATCH!!
	CMP	AL,4 ;SINGLE?
	JNZ	??L006
	JMP	SNGDPC ;YES, DISPATCH!!
??L006:
	JAE	DBLDPC ;MUST BE DOUBLE, DISPATCH!!
VALNSM:	MOV	DH,AL ;SAVE IN [D]
	MOV	AL,CH ;CHECK FOR DOUBLE
	CMP	AL,8 ;PRECISION ENTRY ON THE STACK
	JZ	STKDBL ;FORCE FAC TO DOUBLE
	MOV	AL,DH ;GET VALTYPE OF FAC
	CMP	AL,8 ;AND IF SO, CONVERT THE STACK OPERAND
	JZ	FACDBL ;TO DOUBLE PRECISION
	MOV	AL,CH ;SEE IF THE STACK ENTRY IS SINGLE
	CMP	AL,4 ;PRECISION AND IF SO, CONVERT
	JZ	STKSNG ;THE FAC TO SINGLE PRECISION
	MOV	AL,DH ;SEE IF THE FAC IS SINGLE PRECISION
	CMP	AL,3 ;AND IF SO CONVERT THE STACK TO SINGLE
	JNZ	??L007
	JMP	TMERR ;BLOW UP ON RIGHT HAND STRING OPERAND
??L007:
	JAE	FACSNG ;PRECISION
;NOTE: THE STACK MUST BE INTEGER AT THIS POINT
INTDPC:	MOV	BX,INTDSP ;INTEGER INTEGER CASE
	MOV	CH,0 ;SPECIAL DISPATCH FOR SPEED
	ADD	BX,CX ;[H,L] POINTS TO THE ADDRESS TO GO TO 
	ADD	BX,CX
db 0o56 ;FETCH FROM CODE SEGMENT
	MOV	CL,byte [BX] ;[B,C]=ROUTINE ADDRESS
	INC	BX
db 0o56 ;FETCH FROM CODE SEGMENT
	MOV	CH,byte [BX]
	POP	DX ;[D,E]=LEFT HAND OPERAND
	MOV BX, [FACLO] ;[H,L]=RIGHT HAND OPERAND
	PUSH	CX ;DISPATCH
	RET
;
; THE STACK OPERAND IS DOUBLE PRECISION, SO
; THE FAC MUST BE FORCED TO DOUBLE PRECISION, MOVED INTO ARG
; AND THE STACK VALUE POPED INTO THE FAC
;
STKDBL:	CALL	FRCDBL ;MAKE THE FAC DOUBLE PRECISION
DBLDPC:	CALL	VMOVAF ;MOVE THE FAC INTO ARG
	POP	BX ;POP OFF THE STACK OPERAND INTO THE FAC
	MOV [DFACLO+2], BX
	POP	BX
	MOV [DFACLO], BX ;STORE LOW BYTES AWAY
SNGDBL:	pop cx
pop dx ;POP OFF A FOUR BYTE VALUE
	CALL	MOVFR ;INTO THE FAC
SETDBL:	CALL	FRCDBL ;MAKE SURE THE LEFT OPERAND IS
;DOUBLE PRECISION
	MOV	BX,DBLDSP ;DISPATCH TO A DOUBLE PRECISION ROUTINE
DODSP:	MOV AL, byte [OPRTYP] ;RECALL WHICH OPERAND IT WAS
	ROL	AL,1 ;CREATE A DISPATCH OFFSET, SINCE
;TABLE ADDRESSES ARE TWO BYTES
	ADD	AL,BL ;ADD LOW BYTE OF ADDRESS
	MOV	BL,AL ;SAVE BACK
	ADC	AL,BH ;ADD HIGH BYTE
	SUB	AL,BL ;SUBTRACT LOW
	MOV	BH,AL ;RESULT BACK
db 0o56 ;FETCH FROM CODE SEGMENT
	MOV	BX,[BX] ;FETCH THE ADDRESS
	JMP	BX ;AND PERFORM THE OPERATION, RETURNING
;TO RETAOP, EXCEPT FOR COMPARES WHICH
;RETURN TO DOCMP
;
; THE FAC IS DOUBLE PRECISION AND THE STACK IS EITHER
; INTEGER OR SINGLE PRECISION AND MUST BE CONVERTED
; 
FACDBL:	MOV	AL,CH ;GET THE VALUE TYPE INTO [A]
	PUSH	AX ;SAVE THE STACK VALUE TYPE
	CALL	VMOVAF ;MOVE THE FAC INTO ARG
	POP	AX ;POP THE STACK VALUE TYPE INTO [A]
	MOV byte [VALTYP], AL ;PUT IT IN VALTYP FOR THE FORCE
;ROUTINE
	CMP	AL,4 ;SEE IF ITS SINGLE, SO WE KNOW
;HOW TO POP THE VALUE OFF
	JZ	SNGDBL ;IT'S SINGLE PRECISION
;SO DO A POPR / CALL MOVFR
	POP	BX ;POP OFF THE INTEGER VALUE
	MOV [FACLO], BX ;SAVE IT FOR CONVERSION
	JMP	SETDBL ;SET IT UP
;
; THIS IS THE CASE WHERE THE STACK IS SINGLE PRECISION
; AND THE FAC IS EITHER SINGLE PRECISION OR INTEGER
;
STKSNG:	CALL	FRCSNG ;CONVERT THE FAC IF NECESSARY
SNGDPC:	pop cx
pop dx ;PUT THE LEFT HAND OPERAND IN THE REGISTERS
SNGDO:	MOV	BX,SNGDSP ;SETUP THE DISPATCH ADDRESS
;FOR THE SINGLE PRECISION OPERATOR ROUTINES
	JMP	DODSP ;DISPATCH
;
; THIS IS THE CASE WHERE THE FAC IS SINGLE PRECISION AND THE STACK
; IS AN INTEGER. 
;
FACSNG:	POP	BX ;POP OFF THE INTEGER ON THE STACK
	CALL	PUSHF ;SAVE THE FAC ON THE STACK
	CALL	CONSIH ;CONVERT [H,L] TO A SINGLE PRECISION
;NUMBER IN THE FAC
	CALL	MOVRF ;PUT THE LEFT HAND OPERAND IN THE REGISTERS
	POP	BX ;RESTORE THE FAC
	MOV [FAC-1], BX ;FROM THE STACK
	POP	BX
	MOV [FACLO], BX
	JMP	SNGDO ;PERFORM THE OPERATION
;
; HERE TO DO INTEGER DIVISION. SINCE WE WANT 1/3 TO BE
; .333333 AND NOT ZERO WE HAVE TO FORCE BOTH ARGUMENTS
; TO BE SINGLE-PRECISION FLOATING POINT NUMBERS
; AND USE FDIV
;
global INTDIV
INTDIV:	PUSH	BX ;SAVE THE RIGHT HAND ARGUMENT
	XCHG	BX,DX ;[H,L]=LEFT HAND ARGUMENT
	CALL	CONSIH ;CONVERT [H,L] TO A SINGLE-PRECISION
;NUMBER IN THE FAC
	POP	BX ;GET BACK THE RIGHT HAND ARGUMENT
	CALL	PUSHF ;PUSH THE CONVERTED LEFT HAND ARGUMENT
;ONTO THE STACK
	CALL	CONSIH ;CONVERT THE RIGHT HAND ARGUMENT TO A
;SINGLE PRECISION NUMBER IN THE FAC
	JMP	FDIVT
;REGISTERS THE LEFT HAND ARGUMENT
; SUBTTL EVAL - EVALUATE VARIABLE, CONSTANT, FUNCTION CALL
global EVAL
EVAL:
	CALL	CHRGTR
	JNZ	??L008
	JMP	MOERR ;TEST FOR MISSING OPERAND - IF NONE GIVE ERROR
??L008:
	JAE	??L009
	JMP	FIN ;IF NUMERIC, INTERPRET CONSTANT
??L009:
	CALL	ISLET2 ;VARIABLE NAME?
	JNAE	??L010
	JMP	ISVAR ;AN ALPHABETIC CHARACTER MEANS YES
??L010:
	CMP	AL,DBLCON+1 ;IS IT AN EMBEDED CONSTANT
	JAE	??L011
	JMP	CONFAC ;RESCAN THE TOKEN & RESTORE OLD TEXT PTR
??L011:
extern EVALX
	CALL	EVALX ;Handle extended functions.
	INC	AL ;IS IT A FUNCTION CALL (PRECEDED BY 377)
	JNZ	??L012
	JMP	ISFUN ;YES, DO IT
??L012:
	DEC	AL ;FIX A BACK
	CMP	AL,PLUSTK ;IGNORE "+"
	JZ	EVAL
	CMP	AL,MINUTK ;NEGATION?
	JNZ	??L013
	JMP	DOMIN
??L013:
	CMP	AL,34 ;STRING CONSTANT?
	JNZ	??L014
	JMP	STRLTI ;IF SO BUILD A DESCRIPTOR IN A TEMPORARY
??L014:
;DESCRIPTOR LOCATION AND PUT A POINTER TO THE
;DESCRIPTOR IN FACLO.
	CMP	AL,NOTTK ;CHECK FOR "NOT" OPERATOR
	JNZ	??L015
	JMP	NOTER
??L015:
	CMP	AL,"&" ;OCTAL CONSTANT?
	JNZ	??L016
	JMP	OCTCNS
??L016:
	CMP	AL,ERCTK
	JNZ	NTERC ;NO, TRY OTHER POSSIBILITIES
	CALL	CHRGTR ;GRAB FOLLOWING CHAR
	MOV AL, byte [ERRFLG] ;GET THE ERROR CODE.
NTDERC:	PUSH	BX ;SAVE TEXT POINTER
	CALL	SNGFLT ;RETURN THE VALUE
	POP	BX ;RESTORE TEXT POINTER
	RET ;ALL DONE.
NTERC:	CMP	AL,ERLTK ;ERROR LINE NUMBER VARIABLE.
	JNZ	NTERL ;NO, TRY MORE THINGS.
	CALL	CHRGTR ;GET FOLLOWING CHARACTER
	PUSH	BX ;SAVE TEXT POINTER
	MOV BX, [ERRLIN] ;GET THE OFFENDING LINE #
	CALL	INEG2 ;FLOAT 2 BYTE UNSINGED INT
	POP	BX ;RESTORE TEXT POINTER
	RET ;RETURN
NTERL:
	CMP	AL,TOK_VARPTR ;VARPTR CALL?
	JNZ	NTVARP ;NO
	CALL	CHRGTR ;EAT CHAR AFTER
extern VARPT2
	CMP	AL,"$"
	JNZ	??L017
	JMP	VARPT2 ;branch if VARPTR$(x)
??L017:
	CALL	SYNCHR
db "(" ;EAT LEFT PAREN
extern GETPTR
	CMP	AL,"#" ;WANT POINTER TO FILE?
	JNZ	NVRFIL ;NO, MUST BE VARIABLE
	CALL	GTBYTC ;READ FILE #
	PUSH	BX ;SAVE TEXT PTR
	CALL	GETPTR ;GET PTR TO FILE
	POP	BX ;RESTORE TEXT PTR
	JMP	VARRET
NVRFIL:
extern PTRGTN
	CALL	PTRGTN ;GET ADDRESS OF VARIABLE
VARRET:	CALL	SYNCHR
db ")" ;EAT RIGHT PAREN
	PUSH	BX ;SAVE TEXT POINTER
	XCHG	BX,DX ;GET VALUE TO RETURN IN [H,L]
	OR	BX,BX ;MAKE SURE NOT UNDEFINED VAR
;SET CC'S. ZERO IF UNDEF
	JNZ	??L018
	JMP	FCERR ;ALL OVER IF UNDEF (DONT WANT
??L018:
;USER POKING INTO ZERO IF HE'S
;TOO LAZY TO CHECK
	CALL	MAKINT ;MAKE IT AN INT
	POP	BX ;RESTORE TEXT POINTER
	RET
NTVARP:
	CMP	AL,USRTK ;USER ASSEMBLY LANGUAGE ROUTINE??
	JNZ	??L019
	JMP	USRFN ;GO HANDLE IT
??L019:
	CMP	AL,INSRTK ;IS IT THE INSTR FUNCTION??
	JNZ	??L020
	JMP	INSTR ;DISPATCH
??L020:
	CMP	AL,TOK_SCREEN
	JNZ	??L021
extern SCRENF
	JMP	SCRENF
??L021:
	CMP	AL,TOK_POINT
	JNZ	??L022
extern POINT
	JMP	POINT
??L022:
extern INKEY
	CMP	AL,TOK_INKEY ;INKEY$ FUNCTION?
	JNZ	??L023
	JMP	INKEY
??L023:
	CMP	AL,TOK_STRING ;STRING FUNCTION?
	JNZ	??L024
	JMP	STRNG$ ;YES, GO DO IT
??L024:
extern FIXINP
	CMP	AL,TOK_INPUT ;FIXED LENGTH INPUT?
	JNZ	??L025
	JMP	FIXINP ;YES
??L025:
	CMP	AL,CLINTK ;WANT TO KNOW CURRENT LINE ON SCREEN?
	JNZ	??L026
extern GETLIN
	JMP	GETLIN ;YES
??L026:
	CMP	AL,FNTK ;USER-DEFINED FUNCTION?
	JNZ	??L027
	JMP	FNDOER
??L027:
;
; ONLY POSSIBILITY LEFT IS A FORMULA IN PARENTHESES
;
global PARCHK
PARCHK:	CALL	FRMPRN ;RECURSIVELY EVALUATE THE FORMULA
	CALL	SYNCHR
db ")"
	RET
DOMIN:
	MOV	DH,125 ;A PRECEDENCE BELOW ^
;BUT ABOVE ALL ELSE
	CALL	LPOPER ;SO ^ GREATER THAN UNARY MINUS
	MOV BX, [TEMP2] ;GET TEXT POINTER
	PUSH	BX
	CALL	VNEG
LABBCK: ;FUNCTIONS THAT DON'T RETURN
;STRING VALUES COME BACK HERE
	POP	BX
	RET
global ISVAR
ISVAR:	CALL	PTRGET ;GET A POINTER TO THE
;VARIABLE IN [D,E]
global RETVAR
RETVAR:	PUSH	BX ;SAVE THE TEXT POINTER
	XCHG	BX,DX ;PUT THE POINTER TO THE VARIABLE VALUE
;INTO [H,L]. IN THE CASE OF A STRING
;THIS IS A POINTER TO A DESCRIPTOR AND NOT
;AN ACTUAL VALUE
	MOV [FACLO], BX ;IN CASE IT'S STRING STORE THE POINTER
;TO THE DESCRIPTOR IN FACLO.
	CALL	GETYPR ;FOR STRINGS WE JUST LEAVE
	JZ	??L028
	CALL	VMOVFM ;A POINTER IN THE FAC
??L028:
;THE FAC USING [H,L] AS THE POINTER.
	POP	BX ;RESTORE THE TEXT POINTER
	RET
global MAKUPL
MAKUPL:	MOV	AL,byte [BX] ;GET CHAR FROM MEMORY
global MAKUPS
MAKUPS:	CMP	AL,"A"+0o40 ;IS IT LOWER CASE RANGE
	JNB	$+3
	RET ;LESS
	CMP	AL,"Z"+0o41 ;GREATER
	JNAE	$+3
	RET ;TEST
	AND	AL,0o137 ;MAKE UPPER CASE
	RET ;DONE
global CNSGET
CNSGET:
	CMP	AL,"&" ;OCTAL PERHAPS?
	JZ	??L029
	JMP	LINGET
??L029:
global DOL_OHCNS
DOL_OHCNS:
global OCTCNS
OCTCNS:	MOV	DX,0 ;INITIALIZE TO ZERO AND IGNORE OVERFLOW
	CALL	CHRGTR ;GET FIRST CHAR
	CALL	MAKUPS ;MAKE UPPER IF NESC.
	CMP	AL,"O" ;OCTAL?
	JZ	LOPOCT ;IF SO, DO IT
	CMP	AL,"H" ;HEX?
	JNZ	LOPOC2 ;THEN DO IT
	MOV	CH,5 ;INIT DIGIT COUNT
LOPHEX:	INC	BX ;BUMP POINTER
	MOV	AL,byte [BX] ;GET CHAR
	CALL	MAKUPS ;MAKE UPPER CASE
	CALL	ISLET2 ;FETCH CHAR, SEE IF ALPHA
	XCHG	BX,DX ;SAVE [H,L]
	JAE	ALPTST ;YES, MAKE SURE LEGAL HEC
	CMP	AL,"9"+1 ;IS IT BIGGER THAN LARGEST DIGIT?
	JAE	OCTFIN ;YES, BE FORGIVING & RETURN
	SUB	AL,"0" ;CONVERT DIGIT, MAKE BINARY
	JB	OCTFIN ;BE FORGIVING IF NOT HEX DIGIT
	JMP	NXTHEX ;ADD IN OFFSET
ALPTST:	CMP	AL,"F"+1 ;IS IT LEGAL HEX?
	JAE	HEXFIN ;YES, TERMINATE
	SUB	AL,"A"-10 ;MAKE BINARY VALUE
NXTHEX:	ADD	BX,BX ;SHIFT RIGHT FOUR BITS
	ADD	BX,BX
	ADD	BX,BX
	ADD	BX,BX
	OR	AL,BL ;OR ON NEW DIGIT
	MOV	BL,AL ;SAVE BACK
	XCHG	BX,DX ;GET TEXT POINTER BACK IN [H,L]
	DEC	CH
	JNZ	LOPHEX ;KEEP EATING IF NOT TOO MANY DIGITS
;IF NOT INPUT STATEMENT GOTO OVFLW ERROR FROM HERE, ELSE PASS BACK ERROR
CKOVER:	MOV AL, byte [FLGSCN]
	OR	AL,AL
	JNZ	??L030
	JMP	OVERR ;IF NOT INPUT STATEMENT, THIS IS ERROR
??L030:
	PUSH	BX
	MOV	BX,DOL_OVMSG
	CALL	DOL_STPRN ;PRINT OVERFLOW MESSAGE
	CALL	CRDO
	POP	BX
CONER2:	MOV AL, byte [FLGOVC]
	INC	AL
	MOV byte [FLGOVC], AL ;TELL INPUT CODE THAT ERROR OCCURED
	RET
CONERR:	MOV AL, byte [FLGSCN]
	OR	AL,AL
	JZ	??L031
	JMP	CONER2 ;IF INPUT CODE ERROR, RETURN ERROR CODE
??L031:
	JMP	SNERR ;ELSE GOTO ERROR FROM HERE
LOPOC2:	DEC	BX ;REGET LAST CHARACTER
LOPOCT:	CALL	CHRGTR ;READ A DIGIT
	XCHG	BX,DX ;RESULT INTO [H,L]
	JAE	OCTFIN ;OUT OF DIGITS MEANS DONE
	CMP	AL,"8" ;IS THIS AN OCTAL DIGIT
	JNAE	??L032
	JMP	CONERR ;NO, TOO BAD YOU WILL LOSE
??L032:
	MOV	CX,CKOVER ;WHERE TO GO ON OVERFLOW ERROR
	PUSH	CX ;SAVE ADDR ON STACK
	ADD	BX,BX ;MULTIPLY BY EIGHT
	JNB	$+3
	RET ;OVERFLOW ERROR
	ADD	BX,BX
	JNB	$+3
	RET ;OVERFLOW ERROR
	ADD	BX,BX
	JNB	$+3
	RET ;OVERFLOW ERROR
	POP	CX ;GET RID OF OVERR ADDR
	MOV	CH,0 ;SETUP TO ADD [B,C]
	SUB	AL,"0"
	MOV	CL,AL
	ADD	BX,CX ;ADD IN THE DIGIT
	XCHG	BX,DX ;PUT TEXT POINTER BACK IN [H,L]
	JMP	LOPOCT ;SCAN MORE DIGITS
HEXFIN:
OCTFIN:
global HOCFIN
HOCFIN:
	CALL	MAKINT ;SAVE AS AN INTEGER
	XCHG	BX,DX ;[H,L]-TEXT POINTER
	RET
ISFUN:
	INC	BX ;BUMP SOURCE TEXT POINTER
	MOV	AL,byte [BX] ;GET THE ACTUAL TOKEN FOR FN
	SUB	AL,ONEFUN ;MAKE INTO OFFSET
extern RNDMON
	CMP	AL,DOL_RNDFN ;IS IT RND?
	JNZ	NTMRND ;IF NOT NO NEED TO CHECK MONADIC
	PUSH	BX ;SAVE TEXT POINTER
	CALL	CHRGTR ;SEE IF NEXT CHAR IS "("
	CMP	AL,"("
	POP	BX ;GET BACK THE OLD TEXT POINTER
	JZ	??L033
	JMP	RNDMON ;HANDLE MONADIC CASE
??L033:
	MOV	AL,DOL_RNDFN
NTMRND:
	MOV	CH,0
	ROL	AL,1 ;MULTIPLY BY 2
	MOV	CL,AL
	PUSH	CX ;SAVE THE FUNCTION # ON THE STACK
	CALL	CHRGTR
	MOV	AL,CL ;LOOK AT FUNCTION #
	CMP	AL,NUMGFN ;IS IT PAST LASNUM?
	JAE	OKNORM ;NO, MUST BE A NORMAL FUNCTION
;
; MOST FUNCTIONS TAKE A SINGLE ARGUMENT.
; THE RETURN ADDRESS OF THESE FUNCTIONS IS A SMALL ROUTINE
; THAT CHECKS TO MAKE SURE VALTYP IS 0 (NUMERIC) AND POPS OFF
; THE TEXT POINTER. SO NORMAL FUNCTIONS THAT RETURN STRING RESULTS (I.E. CHR$)
; MUST POP OFF THE RETURN ADDRESS OF LABBCK, AND POP OFF THE
; TEXT POINTER AND THEN RETURN TO FRMEVL.
;
; THE SO CALLED "FUNNY" FUNCTIONS CAN TAKE MORE THAN ONE ARGUMENT.
; THE FIRST OF WHICH MUST BE STRING AND THE SECOND OF WHICH
; MUST BE A NUMBER BETWEEN 0 AND 256. THE TEXT POINTER IS
; PASSED TO THESE FUNCTIONS SO ADDITIONAL ARGUMENTS
; CAN BE READ. THE TEXT POINTER IS PASSED IN [D,E].
; THE CLOSE PARENTHESIS MUST BE CHECKED AND RETURN IS DIRECTLY
; TO FRMEVL WITH [H,L] SETUP AS THE TEXT POINTER POINTING BEYOND THE ")".
; THE POINTER TO THE DESCRIPTOR OF THE STRING ARGUMENT
; IS STORED ON THE STACK UNDERNEATH THE VALUE OF THE INTEGER
; ARGUMENT (2 BYTES)
;
; FIRST ARGUMENT ALWAYS STRING -- SECOND INTEGER
;
	CALL	FRMPRN ;EAT OPEN PAREN AND FIRST ARG
	CALL	SYNCHR
db 44 ;TWO ARGS SO COMMA MUST DELIMIT
	CALL	CHKSTR ;MAKE SURE THE FIRST ONE WAS STRING
	XCHG	BX,DX ;[D,E]=TXTPTR
	MOV BX, [FACLO] ;GET PTR AT STRING DESCRIPTOR
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;GET FUNCTION #
;SAVE THE STRING PTR
	PUSH	BX ;PUT THE FUNCTION # ON
	XCHG	BX,DX ;[H,L]=TXTPTR
	CALL	GETBYT ;[E]=VALUE OF FORMULA
	XCHG	BX,DX ;TEXT POINTER INTO [D,E]
;[H,L]=INT VALUE OF SECOND ARGUMENT
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;SAVE INT VALUE OF SECOND ARG
;[H,L]=FUNCTION NUMBER
	JMP	FINGO ;DISPATCH TO FUNCTION
OKNORM:
	CALL	PARCHK ;CHECK OUT THE ARGUMENT
;AND MAKE SURE ITS FOLLOWED BY ")"
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;[H,L]=FUNCTION # AND SAVE TEXT POINTER
;
; CHECK IF SPECIAL COERCION MUST BE DONE FOR ONE OF THE TRANSCENDENTAL
; FUNCTIONS (RND, SQR, COS, SIN, TAN, ATN, LOG, AND EXP)
; THESE FUNCTIONS DO NOT LOOK AT VALTYP, BUT RATHER ASSUME THE
; ARGUMENT PASSED IN THE FAC IS SINGLE PRECISION, SO FRCSNG
; MUST BE CALLED BEFORE DISPATCHING TO THEM.
;
	MOV	AL,BL ;[A]=FUNCTION NUMBER
	CMP	AL,BOTCON ;LESS THAN SQUARE ROOT?
	JB	NOTFRF ;DON'T FORCE THE ARGUMENT
	CMP	AL,TOPCON ;BIGGER THAN ARC-TANGENT?
	PUSH	BX ;SAVE THE FUNCTION NUMBER
	JNB	??L034
	CALL	FRCSNG ;IF NOT, FORCE FAC TO SINGLE-PRECISION
??L034:
	POP	BX ;RESTORE THE FUNCTION NUMBER
NOTFRF:
	MOV	DX,LABBCK ;RETURN ADDRESS
	PUSH	DX ;MAKE THEM REALLY COME BACK
	MOV	AL,1 ;FUNCTION SHOULD ONLY PRINT OVERFLOW ONCE
	MOV byte [FLGOVC], AL
FINGO:
	MOV	CX,FUNDSP ;FUNCTION DISPATCH TABLE
DISPAT:	ADD	BX,CX ;ADD ON THE OFFSET
db 0o56 ;FETCH FROM CODE SEGMENT
db 0o377, 0o047 ;JMPI   0(.BX)
; THE FOLOWING ROUTINE IS CALLED FROM FIN IN F4
; TO SCAN LEADING SIGNS FOR NUMBERS. IT WAS MOVED
; TO F3 TO ELIMINATE BYTE EXTERNALS
global MINPLS
MINPLS:
	DEC	DH ;SET SIGN OF EXPONENT FLAG
	CMP	AL,MINUTK ;NEGATIVE EXPONENT?
	JNZ	$+3
	RET
	CMP	AL,"-"
	JNZ	$+3
	RET
	INC	DH ;NO, RESET FLAG
	CMP	AL,"+"
	JNZ	$+3
	RET
	CMP	AL,PLUSTK ;IGNORE "+"
	JNZ	$+3
	RET
	LAHF
	DEC	BX ;CHECK IF LAST CHARACTER WAS A DIGIT
	SAHF
	RET ;RETURN WITH NON-ZERO SET
; SUBTTL MORE FORMULA EVALUATION - LOGICAL, RELATIONAL OPS
DOCMP:	INC	AL ;SETUP BITS
	ADC	AL,AL ;4=LESS 2=EQUAL 1=GREATER
	POP	CX ;WHAT DID HE WANT?
	AND	AL,CH ;ANY BITS MATCH?
	ADD	AL,255 ;MAP 0 TO 0
	SBB	AL,AL ;AND ALL OTHERS TO 377
	CALL	CONIA ;CONVERT [A] TO AN INTEGER SIGNED
	JMP	RETAPG ;RETURN FROM OPERATOR APPLICATION
NOTER:	MOV	DH,90 ;"NOT" HAS PRECEDENCE 90, SO
	CALL	LPOPER ;FORMULA EVALUATION IS ENTERED WITH A DUMMY
;ENTRY OF 90 ON THE STACK
	CALL	FRCINT ;COERCE THE ARGUMENT TO INTEGER
db 0o367, 0o323 ;NOT [H,L]
	MOV [FACLO], BX ;UPDATE THE FAC
	POP	CX ;FRMEVL, AFTER SEEING THE PRECEDENCE
;OF 90 THINKS IT IS APPLYING AN OPERATOR
;SO IT HAS THE TEXT POINTER IN TEMP2 SO
RETAPG:	JMP	RETAOP ;RETURN TO REFETCH IT
global GETYPR
GETYPR:	MOV AL, byte [VALTYP] ;REPLACEMENT FOR "GETYPE" RST
	CMP	AL,8
;
; CONTINUATION OF GETYPE RST
;
CGETYP:	DEC	AL ;SET THE OTHER CONDITION CODES CORRECTLY
	DEC	AL ; WITHOUT AFFECTING CARRY
	DEC	AL
	RET
;
; DANDOR APPLIES THE "AND" AND "OR" OPERATORS
; AND SHOULD BE USED TO IMPLEMENT ALL LOGICAL OPERATORS.
; WHENEVER AN OPERATOR IS APPLIED, ITS PRECEDENCE IS IN [B].
; THIS FACT IS USED TO DISTINGUISH BETWEEN "AND" AND "OR".
; THE RIGHT HAND ARGUMENT IS COERCED TO INTEGER, JUST AS
; THE LEFT HAND ONE WAS WHEN IT WAS PUSHED ON THE STACK.
;
DANDOR:
	MOV	AL,CH ;GET THE PRECEDENCE
	PUSH	AX ;SAVE THE PRECEDENCE "OR"=70
	CALL	FRCINT ;COERCE RIGHT HAND ARGUMENT TO INTEGER
	POP	AX ;GET BACK THE PRECEDENCE TO DISTINGUISH
;"AND" AND "OR"
	POP	DX ;POP OFF THE LEFT HAND ARGUMENT
	CMP	AL,122 ;IS THE OPERATOR "MOD"?
	JNZ	??L035
	JMP	IMOD ;IF SO, USE MONTE'S SPECIAL ROUTINE
??L035:
	CMP	AL,123 ;IS THE OPERATOR "IDIV"?
	JNZ	??L036
	JMP	IDIV ;LET MONTE HANDLE IT
??L036:
	MOV	CX,MAKINT ;PLACE TO RETURN WHEN DONE
	PUSH	CX ;SAVE ON STACK
	CMP	AL,70 ;SET ZERO FOR "OR"
	JNZ	NOTOR
db 0o13, 0o332 ;OR BX,BX
	RET ;RETURN THE INTEGER [A,L]
NOTOR:
	CMP	AL,80 ;AND?
	JNZ	NOTAND
db 0o43, 0o332 ;AND BX,DX
	RET ;RETURN THE INTEGER [A,L]
NOTAND:	CMP	AL,60 ;XOR?
	JNZ	NOTXOR ;NO
db 0o63, 0o332 ;XOR BX,DX
	RET
NOTXOR:	CMP	AL,50 ;EQV?
	JNZ	NOTEQV ;NO
db 0o63, 0o332 ;XOR BX,DX
db 0o367, 0o323 ;NOT BX
	RET
;FOR "IMP" USE A IMP B = NOT(A AND NOT(B))
NOTEQV:
db 0o367, 0o323 ;NOT BX
db 0o43, 0o332 ;AND BX,DX
db 0o367, 0o323 ;NOT BX
	RET
;
; THIS ROUTINE SUBTRACTS [D,E] FROM [H,L]
; AND FLOATS THE RESULT LEAVING IT IN FAC.
;
global GIVDBL
GIVDBL:	SUB	BX,DX ;[H,L]=[H,L]-[D,E]
	JMP	INEG2 ;FLOAT 2 BYTE UNSIGNED INT
global SNGFLT
SNGFLT:	MOV	BL,AL ;MAKE [A] AN UNSIGNED INTEGER
	XOR	AL,AL
global GIVINT
GIVINT:	MOV	BH,AL
	JMP	MAKINT
; SUBTTL USER DEFINED (USR) ASSEMBLY LANGUAGE FUNCTION CODE
USRFN:
extern PRODIR
	CALL	PRODIR ;Don't allow in direct mode in
; protected environment
	CALL	SCNUSR ;SCAN THE USR#
	PUSH	DX ;SAVE POINTER
	CALL	PARCHK ;EAT LEFT PAREN AND FORMULA
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;SAVE TEXT POINTER & GET INDEX INTO USRTAB
	MOV	DX,[BX] ;GET DISPATCH ADDRESS
db 0o203, 0o372 ;CMPI DX,
db 0o377 ; 0FFFFH
	JNZ	??L037
	JMP	FCERR ;GIVE HIM AN ERROR IF HE CALLS A SUBROUTINE
??L037:
;AT FFFF, SINCE CANT INITIALIZE TABLE
;TO "FCERR" SINCE IT MAY NOT EXIST IN
;THE DESTINATION SEGMENT
db 0o16 ;PUSH CS - PUSH BASIC'S CODE SEGMENT
	MOV	BX,POPHRT ;GET ADDRESS OF POP H RET
	PUSH	BX ;PUSH IT ON
db 0o377
db 0o66
dw SAVSEG ;PUSH ON SEGMENT ADDRESS OF SUBROUTINE
	PUSH	DX ;SAVE ADDRESS OF USR ROUTINE
	MOV AL, byte [VALTYP] ;GET ARGUMENT TYPE IN [A]
	PUSH	AX ;SAVE VALTYP
	CMP	AL,3 ;STRING??
	JNZ	??L038
	CALL	FREFAC ;FREE IT UP
??L038:
	POP	AX ;GET BACK VALTYP
	XCHG	BX,DX ;MOVE POSSIBLE DESC. POINTER TO [D,E]
	MOV	BX,FACLO ;POINTER TO FAC IN [H,L]
db 0o313 ;INTER SEGMENT RETURN
SCNUSR:	CALL	CHRGTR ;GET A CHAR
	MOV	CX,0 ;ASSUME USR0
	CMP	AL,ONECON+10 ;SINGLE BYTE INT EXPECTED
	JAE	NOARGU ;NO, MUST BE DEFAULTING TO USR0
	CMP	AL,ONECON ;IS IT SMALLER THAN ONECON
	JB	NOARGU ;YES, ASSUME TRYING TO DEFAULT TO USR0
USERCN:	CALL	CHRGTR ;SCAN PAST NEXT CHAR
	MOV AL, byte [CONLO] ;GET VALUE OF 1 BYTER
	OR	AL,AL ;MAKE SURE CARRY IS OFF
	RCL	AL,1 ;MULTIPLY BY 2
	MOV	CL,AL ;SAVE OFFSET IN [C]
NOARGU:	XCHG	BX,DX ;SAVE TEXT POINTER IN [D,E]
	MOV	BX,USRTAB ;GET START OF TABLE
	ADD	BX,CX ;ADD ON OFFSET
	XCHG	BX,DX ;RESTORE TEXT POINTER, ADDRESS TO [D,E]
	RET ;RETURN FROM SCAN ROUTINE
DEFUSR:	CALL	SCNUSR ;SCAN THE USR NAME
	PUSH	DX ;SAVE POINTER TO USRTAB ENTRY
	CALL	SYNCHR
db EQULTK ;MUST HAVE EQUAL SIGN
	CALL	FRMQNT ;GET THE ADDRESS
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;TEXT POINTER TO STACK, GET ADDRESS
	MOV	[BX],DX ;SAVE USR CALL ADDRESS
	POP	BX ;RESTORE TEXT POINTER
	RET ;RETURN TO NEWSTT
; SUBTTL SIMPLE-USER-DEFINED-FUNCTION CODE
;
; IN THE 8K VERSION (SEE LATER COMMENT FOR EXTENDED)
; NOTE ONLY SINGLE ARGUMENTS ARE ALLOWED TO FUNCTIONS
; AND FUNCTIONS MUST BE OF THE SINGLE LINE FORM:
; DEF FNA(X)=X^2+X-2
; NO STRINGS CAN BE INVOLVED WITH THESE FUNCTIONS
;
; IDEA: CREATE A FUNNY SIMPLE VARIABLE ENTRY
; WHOSE FIRST CHARACTER (SECOND WORD IN MEMORY)
; HAS THE 200 BIT SET.
; THE VALUE WILL BE:
;
;       A TXTPTR TO THE FORMULA
;       THE NAME OF THE PARAMETER VARIABLE
;
; FUNCTION NAMES CAN BE LIKE "FNA4"
;
DEF:
	CMP	AL,USRTK ;DEFINING THE CALL ADDRESS OF USR ROUTINE?
	JZ	DEFUSR ;YES, DO IT
	CMP	AL,FNTK ; "FN"?
	JZ	DEFNC3 ;THEN GO DO FUNCTION NAME
	CALL	SYNCHR
db "S" ;Else must be "SEG" or error.
	CALL	SYNCHR
db "E"
	CALL	SYNCHR
db "G"
db 0o214, 0o332 ; MOV DX,DS
	JZ	DEFNC2 ;NO ASSIGNMENT, USE CURRENT [DS].
	CALL	SYNCHR
db EQULTK ; ELSE MUST HAVE EQUAL SIGN
	CALL	FRMQNT ;GET SEGMENT IN DX
DEFNC2:	MOV [SAVSEG], DX ;STORE FOR PEEK/POKE/CALL/BLOAD/BSAVE
	RET ;RETURN TO NEWSTT
DEFNC3:
	CALL	GETFNM ;GET A POINTER TO THE FUNCTION NAME
	CALL	ERRDIR ;DEF IS "ILLEGAL DIRECT"
	XCHG	BX,DX ;[D,E] = THE TEXT POINTER AFTER THE FUNCTION
;NAME AND [H,L] = POINTER AT PLACE TO STORE
;VALUE OF THE FUNCTION VARIABLE
	MOV	[BX],DX ;SAVE THE TEXT POINTER AS THE VALUE
	XCHG	BX,DX ;RESTORE THE TEXT POINTER TO [H,L]
	MOV	AL,byte [BX] ;GET NEXT CHAR
	CMP	AL,"(" ;DOES THIS FUNCTION HAVE ARGS?
	JZ	??L039
	JMP	DATA ;NO
??L039:
	CALL	CHRGTR
SCNLIS:	CALL	PTRGET ;GET POINTER TO DUMMY VAR(CREATE VAR)
	MOV	AL,byte [BX] ;GET TERMINATOR
	CMP	AL,")" ;END OF ARG LIST?
	JNZ	??L040
	JMP	DATA ;YES
??L040:
	CALL	SYNCHR
db 44 ;"," MUST FOLLOW THEN
	JMP	SCNLIS
FNDOER:	CALL	GETFNM ;GET A POINTER TO
	MOV AL, byte [VALTYP] ;FIND OUT WHAT KIND OF FUNCTION IT IS
	OR	AL,AL ;PUSH THIS [A] ON WITH A PSW WITH CARRY OFF
;SO THAT WHEN VALUES ARE BEING POPPED OFF
;AND RESTORED TO PARAMETERS WE WILL KNOW
;WHEN TO STOP
;WHEN A VALTYP IS POPPED OFF WITH
;CARRY OFF
	PUSH	AX ;SAVE SO THAT THE FINAL RESULT WILL
;BE COERCED TO THE FUNCTION TYPE
	MOV [TEMP2], BX ;SAVE THE TEXT POINTER THAT POINTS PAST
;THE FUNCTION NAME IN THE CALL
	XCHG	BX,DX ;[H,L]=A POINTER TO THE VALUE OF FUNCTION
	MOV	BX,[BX] ;[H,L]=VALUE OF THE FUNCTION
;WHICH IS A TEXT POINTER AT THE FORMAL
;PARAMETER LIST IN THE DEFINITION
	OR	BX,BX ;A ZERO TEXT POINTER MEANS THE FUNCTION
;WAS NEVER DEFINED
	JNZ	??L041
	JMP	UFERR ;IF SO, GIVEN AN "UNDEFINED FUNCTION" ERROR
??L041:
	MOV	AL,byte [BX] ;SEE IF THERE ARE ANY PARAMETERS
	CMP	AL,"(" ;PARAMETER LIST STARTS WITH "(""
	JZ	??L042
	JMP	FINVLS ;SKIP OVER PARAMETER SETUP
??L042:
	CALL	CHRGTR ;GO PAST THE "("
	MOV [TEMP3], BX ;SAVE THE TEXT POINTER TO THE START OF THE
	XCHG	BX,DX ;PARAMETER LIST.
	MOV BX, [TEMP2] ;NOW GET THE TEXT-POINTER FROM THE CALL
;WHICH IS POINTING JUST PAST THE
;FUNCTION NAME AT THE ARGUMENT LIST
	CALL	SYNCHR
db "(" ;MAKE SURE THE ARGUMENT LIST IS THERE
	XOR	AL,AL ;INDICATE END OF VALUES TO ASSIGN
	PUSH	AX
	PUSH	BX ;SAVE THE CALLERS TEXT POINTER
	XCHG	BX,DX ;GET THE POINTER TO THE BEGINNING OF THE
;PARAMETER LIST
ASGMOR:	MOV	AL,128 ;OUTLAW ARRAYS WHEN SCANNING
	MOV byte [SUBFLG], AL ;PARAMETERS
	CALL	PTRGET ;READ A PARAMETER
	XCHG	BX,DX ;[D,E]=PARAMETER LIST TEXT,[H,L]=VARIABLE POINTER
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;SAVE THE VARIABLES POSITION AND
;GET THE POINTER AT THE ARG LIST
	MOV AL, byte [VALTYP] ;AND ITS TYPE (FOR COERCION)
	PUSH	AX
	PUSH	DX ;SAVE THE TEXT POINTER INTO THE PARAMETER
	CALL	FRMEVL ;EVALUATE THE ARGUMENT
	MOV [TEMP2], BX ;SAVE THE ARGUMENT LIST POINTER
	POP	BX ;AND THE PARAMETER LIST POINTER
	MOV [TEMP3], BX
	POP	AX ;GET THE VALUE TYPE
	CALL	DOCNVF ;COERCE THE ARGUMENT
	MOV	CL,4 ;MAKE SURE THERE IS ROOM FOR THE VALUE
	CALL	GETSTK
	MOV	BX,0-8 ;SAVE EIGHT PLACES
	ADD	BX,SP
	MOV	SP,BX
	CALL	VMOVMF ;PUT VALUE INTO RESERVED PLACE IN STACK
	MOV AL, byte [VALTYP] ;SAVE TYPE FOR ASSIGNMENT
	PUSH	AX
	MOV BX, [TEMP2] ;REGET THE ARGUMENT LIST POINTER
	MOV	AL,byte [BX] ;SEE WHAT COMES AFTER THE ARGUMENT FORMULA
	CMP	AL,")" ;IS THE ARGUMENT LIST ENDING?
	JZ	POPASG ;MAKE SURE THE ARGUMENT LIST ALSO ENDED
	CALL	SYNCHR
db 0o54 ;SKIP OVER ARGUMENT COMMA
	PUSH	BX ;SAVE THE ARGUMENT LIST TEXT POINTER
	MOV BX, [TEMP3] ;GET THE TEXT POINTER INTO THE DEFINTION'S
;PARAMETER LIST
	CALL	SYNCHR
db 0o54 ;SKIP OVER THE PARAMETER LIST COMMA
	JMP	ASGMOR ;AND BIND THE REST OF THE PARAMETERS
POPAS2:	POP	AX ;IF ASSIGNMENT IS SUCESSFUL UPDATE PRMLN2
	MOV byte [PRMLN2], AL ;INDICATE NEW VARIABLE IS IN PLACE
POPASG:	POP	AX ;GET THE VALUE TYPE
	OR	AL,AL
	JZ	FINASG ;ZERO MEANS NO MORE LEFT TO POP AND ASSIGN
	MOV byte [VALTYP], AL
	MOV	BX,0 ;POINT INTO STACK
	ADD	BX,SP ;TO GET SAVED VALUE
	CALL	VMOVFM ;PUT VALUE INTO FAC
	MOV	BX,8 ;FREE UP STACK AREA
	ADD	BX,SP
	MOV	SP,BX
	POP	DX ;GET PLACE TO STORE TO
	MOV	BL,3 ;CALCULATE THE SIZE OF THE LOOKS (NAME)
LPSIZL:	INC	BL ;INCREMENT SIZE
	DEC	DX ;POINT AT PREVIOUS CHARACTER
	MOV	SI,DX
	MOV	AL,[SI] ;SEE IF IT IS THE LENGTH OR ANOTHER CHARACTER
	OR	AL,AL
	JNS	??L043
	JMP	LPSIZL ;HIGH BIT INDICATES STILL PART OF NAME
??L043:
	DEC	DX ;BACK UP OVER LOOKS
	DEC	DX
	DEC	DX
	MOV AL, byte [VALTYP] ;GET SIZE OF VALUE
	ADD	AL,BL ;ADD ON SIZE OF NAME
	MOV	CH,AL ;SAVE TOTAL LENGTH IN [B]
	MOV AL, byte [PRMLN2] ;GET CURRENT SIZE OF BLOCK
	MOV	CL,AL ;SAVE IN [C]
	ADD	AL,CH ;GET POTENTIAL NEW SIZE
	CMP	AL,PRMSIZ ;CAN'T EXCEED ALLOCATED STORAGE
	JNAE	??L044
	JMP	FCERR
??L044:
	PUSH	AX ;SAVE NEW SIZE
	MOV	AL,BL ;[A]=SIZE OF NAME
	MOV	CH,0 ;[B,C]=SIZE OF PARM2
	MOV	BX,PARM2 ;BASE OF PLACE TO STORE INTO
	ADD	BX,CX ;[H,L]=PLACE TO START THE NEW VARIABLE
	MOV	CL,AL ;[B,C]=LENGTH OF NAME OF VARIABLE
	CALL	BCTRAN ;PUT IN THE NEW NAME
	MOV	CX,POPAS2 ;PLACE TO RETURN AFTER ASSIGNMENT
	PUSH	CX
	PUSH	CX ;SAVE EXTRA ENTRY ON STACK
	JMP	LETCN4 ;PERFORM ASSIGNMENT ON [H,L] (EXTRA POP D)
FINASG:	MOV BX, [TEMP2] ;GET ARGUMENT LIST POINTER
	CALL	CHRGTR ;SKIP OVER THE CLOSING PARENTHESIS
	PUSH	BX ;SAVE THE ARGUMENT TEXT POINTER
	MOV BX, [TEMP3] ;GET THE PARAMETER LIST TEXT POINTER
	CALL	SYNCHR
db ")" ;MAKE SURE THE PARAMETER LIST
;ENDED AT THE SAME TIME
db 0o260 ; SKIP	;SKIP THE NEXT BYTE WITH "MVI AL,"
FINVLS:	PUSH	DX ;HERE WHEN THERE WERE NO ARGUMENTS
;OR PARAMETERS
;SAVE THE TEXT POINTER OF THE CALLER
	MOV [TEMP3], BX ;SAVE THE TEXT POINTER OF THE FUNCTION
	MOV AL, byte [PRMLEN] ;PUSH PARM1 STUFF ONTO THE STACK
	ADD	AL,4 ;WITH PRMLEN AND PRMSTK (4 BYTES EXTRA)
	PUSH	AX ;SAVE THE NUMBER OF BYTES
	ROR	AL,1 ;NUMBER OF TWO BYTE ENTRIES IN [A]
	MOV	CL,AL
	CALL	GETSTK ;IS THERE ROOM ON THE STACK?
	POP	AX ;[A]=AMOUNT TO PUT ONTO STACK
	MOV	CL,AL
	NOT	AL ;COMPLEMENT [A]
	INC	AL
	MOV	BL,AL
	MOV	BH,255
	ADD	BX,SP
	MOV	SP,BX ;SET UP NEW STACK
	PUSH	BX ;SAVE THE NEW VALUE FOR PRMSTK
	MOV	DX,PRMSTK ;FETCH DATA FROM HERE
	CALL	BCTRAN
	POP	BX
	MOV [PRMSTK], BX ;LINK PARAMETER BLOCK FOR GARBAGE COLLECTION
	MOV BX, [PRMLN2] ;NOW PUT PARM2 INTO PARM1
	MOV [PRMLEN], BX ;SET UP LENGTH
	MOV	CX,BX ;[B,C]=TRANSFER COUNT
	MOV	BX,PARM1
	MOV	DX,PARM2
	CALL	BCTRAN
	MOV	BH,AL ;CLEAR OUT PARM2
	MOV	BL,AL
	MOV [PRMLN2], BX
	MOV BX, [FUNACT] ;INCREMENT FUNCTION COUNT
	INC	BX
	MOV [FUNACT], BX
	MOV	AL,BH
	OR	AL,BL ;SET UP ACTIVE FLAG NON-ZERO
	MOV byte [NOFUNS], AL
	MOV BX, [TEMP3] ;GET BACK THE FUNCTION DEFINITION TEXT POINTER
;       DCX     H               ;DETECT A MULTI-LINE FUNCTION
;       CHRGET                  ;IF THE DEFINITION ENDS NOW
;       JZ      MULFUN          ;IF ENDS, ITS A MULTI-LINE FUNCTION
;SKIP OVER THE "=" IN THE DEFINITION
	CALL	FRMEQL ;AND EVALUATE THE DEFINITION FORMULA
;CAN HAVE RECURSION AT THIS POINT
	DEC	BX
	CALL	CHRGTR ;SEE IF THE STATEMENT ENDED RIGHT
	JZ	??L045
	JMP	SNERR ;THIS IS A CHEAT, SINCE THE LINE
??L045:
;NUMBER OF THE ERROR WILL BE THE CALLERS
;LINE # INSTEAD OF THE DEFINITIONS LINE #
	CALL	GETYPR ;SEE IT THE RESULT IS A STRING
	JNZ	NOCPRS ;WHOSE DESCRIPTOR IS ABOUT TO BE WIPED OUT
;BECAUSE IT IS SITTING IN PARM1 (THIS
; HAPPENS IT THE FUNCTION IS A PROJECTION
; FUNCTION ON A STRING ARGUMENT)
	MOV	DX,DSCTMP ;DSCTMP IS PAST ALL THE TEMP AREA
	MOV BX, [FACLO] ;GET THE ADDRESS OF THE DESCRIPTOR
	CMP	BX,DX
	JB	NOCPRS ;RESULT IS A TEMP - NO COPY NESC
	CALL	STRCPY ;MAKE A COPY IN DSCTMP
	CALL	PUTTMP ;PUT RESULT IN A TEMP AND MAKE FACLO POINT AT IT
NOCPRS:	MOV BX, [PRMSTK] ;GET PLACE TO RESTORE PARM1 FROM STACK
	MOV	DH,BH
	MOV	DL,BL
	INC	BX ;POINT AT LENGTH
	INC	BX
	MOV	CL,byte [BX] ;[B,C]=LENGTH
	INC	BX
	MOV	CH,byte [BX]
	INC	CX ;INCLUDE EXTRA BYTES
	INC	CX
	INC	CX
	INC	CX
	MOV	BX,PRMSTK ;PLACE TO STORE INTO
	CALL	BCTRAN
	XCHG	BX,DX ;[D,E]=PLACE TO RESTORE STACK TO
	MOV	SP,BX
	MOV BX, [FUNACT] ;DECREASE ACTIVE FUNCTION COUNT
	DEC	BX
	MOV [FUNACT], BX
	MOV	AL,BH
	OR	AL,BL ;SET UP FUNCTION FLAG
	MOV byte [NOFUNS], AL
	POP	BX ;GET BACK THE CALLERS TEXT POINTER
	POP	AX ;GET BACK THE TYPE OF THE FUNCTION
global DOCNVF
DOCNVF:	PUSH	BX ;SAVE THE TEXT POINTER
	AND	AL,7 ;SETUP DISPATCH TO FORCE
;FORMULA TYPE TO CONFORM
;TO THE VARIABLE ITS BEING ASSIGNED TO
	MOV	BX,FRCTBL ;TABLE OF FORCE ROUTINES
	MOV	CL,AL ;[B,C]=TWO BYTE OFFSET
	MOV	CH,0
	ADD	BX,CX
	CALL	DISPAT ;DISPATCH
	POP	BX ;GET BACK THE TEXT POINTER
	RET
;
; BLOCK TRANSFER ROUTINE WITH SOURCE IN [D,E] DESTINATION IN [H,L]
; AND COUNT IN [B,C]. TRANSFER IS FORWARD.
;
BCTRAL:	MOV	SI,DX
	MOV	AL,[SI]
	MOV	byte [BX],AL
	INC	BX
	INC	DX
	DEC	CX
BCTRAN:	MOV	AL,CH
	OR	AL,CL
	JNZ	BCTRAL
	RET
;
; SUBROUTINE TO SEE IF WE ARE IN DIRECT MODE AND
; COMPLAIN IF SO
;
ERRDIR:	PUSH	BX ;SAVE THEIR [H,L]
	MOV BX, [CURLIN] ;SEE WHAT THE CURRENT LINE IS
	INC	BX ;DIRECT IS 65,535 SO NOW 0
	OR	BX,BX ;IS IT ZERO NOW?
	POP	BX
	JZ	$+3
	RET ;RETURN IF NOT
	MOV	DL,ERRC_ERRID ;"ILLEGAL DIRECT" ERROR
	JMP	ERROR
;
;
; SUBROUTINE TO GET A POINTER TO A FUNCTION NAME
;
GETFNM:	CALL	SYNCHR
db FNTK ;MUST START WITH "FN"
	MOV	AL,128 ;DONT ALLOW AN ARRAY
	MOV byte [SUBFLG], AL ;DON'T RECOGNIZE THE "(" AS
;THE START OF AN ARRAY REFEREENCE
	OR	AL,byte [BX] ;PUT FUNCTION BIT ON
	MOV	CL,AL ;GET FIRST CHARACTER INTO [C]
	JMP	PTRGT2
; SUBTTL STRING FUNCTIONS - LEFT HAND SIDE MID$
global ISMID$
ISMID$:	CMP	AL,126 ;FUNCTION? (FF - $END)
	JZ	??L046
	JMP	SNERR ;NO, ERROR.
??L046:
	INC	BX ;POINT TO NEXT CHAR
	MOV	AL,byte [BX] ;GET FN DESCRIPTOR
	INC	BX ;POINT TO CHAR AFTER
	CMP	AL,MIDTK ;IS IT MID?
extern LHSMID ;CODE IS IN BISTRS.MAC
	JNZ	??L047
	JMP	LHSMID
??L047:
	JMP	SNERR
; SUBTTL INP, OUT, WAIT, CONSOLE, WIDTH
;
; THE FOLLOWING FUNCTIONS ALLOW THE 
; USER FULL ACCESS TO THE 8080/Z80  I/O PORTS
; INP(CHANNEL#) RETURNS AN INTEGER WHICH IS THE STATUS
; OF THE CHANNEL. OUT CHANNEL#,VALUE PUTS OUT THE INTEGER
; VALUE ON CHANNEL #. IT IS A STATEMENT, NOT A FUNCTION.
;
FNINP:
	CALL	FRQINT ;MAKE ARGUMENT AN INTEGER CHANNEL NUMBER
	XCHG	BX,DX
db 0o354 ;READ BYTE INTO AL FROM DX=[D,E] FOR 8086
	JMP	SNGFLT
SETIO:
	CALL	FRMQNT ;READ A 16-BIT PORT FOR Z80 AND 8086
	PUSH	DX ;SAVE FOR USE BY WAIT AND FNOUT
	CALL	SYNCHR
db 44
	CALL	GETBYT ;READ THE DATA BYTE TO [A] AND [E]
	POP	DX ;RETURN PORT IN [D,E]=DX FOR 8086
	RET
FNOUT:	CALL	SETIO ;GET PORT IN [B,C] AND DATA IN [A] & [E]
db 0o356 ;OUTPUT TO PORT DX=[D,E] FROM [A]
	RET
;
; THE WAIT CHANNEL#,MASK,MASK2 WAITS UNTIL THE STATUS
; RETURNED BY CHANNEL# IS NON ZERO WHEN XORED WITH MASK2
; AND THEN ANDED WITH MASK. IF MASK2 IS NOT PRESENT IT IS ASSUMED
; TO BE ZERO.
;
FNWAIT:	CALL	SETIO ;SET UP FOR WAIT
	PUSH	DX ;SAVE THE I/O PORT
	PUSH	AX ;SAVE THE MASK
	MOV	DL,0 ;DEFAULT MASK2 TO ZERO
	DEC	BX
	CALL	CHRGTR ;SEE IF THE STATEMENT ENDED
	JZ	NOTTHR ;IF NO THIRD ARGUMENT SKIP THIS
	CALL	SYNCHR
db 44 ;MAKE SURE THERE IS A ","
	CALL	GETBYT
NOTTHR:	POP	AX ;REGET THE "AND" MASK
	MOV	DH,AL ;KEEP AND MASK IN [D]
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;GET BACK THE PORT NUMBER FOR 8086
LOPINP:
extern POLKEY
	CALL	POLKEY ;Exit if User CTRL-C'd.
	XCHG	BX,DX ;GET READY TO READ PORT IN [D,E]
db 0o354 ;READ BYTE INTO [A]
	XCHG	BX,DX
	XOR	AL,DL ;XOR WITH MASK2
	AND	AL,DH ;AND WITH MASK
	JZ	LOPINP ;LOOP UNTIL RESULT IS NON-ZERO
;NOTE: THIS LOOP CANNOT BE CONTROL-C'ED
LOPINX:	POP	BX ;Restore the Text pointer.
	RET
CONSOL:	JMP	SNERR
extern WIDTHS
global GETINT
GETINT:	CALL	CHRGTR
global GETIN2
GETIN2:	CALL	FRMEVL ;EVALUATE A FORMULA
global INTFR2
INTFR2:	PUSH	BX ;SAVE THE TEXT POINTER
	CALL	FRCINT ;CONVERT THE FORMULA TO AN INTEGER IN [H,L]
	XCHG	BX,DX ;PUT THE INTEGER INTO [D,E]
	POP	BX ;RESTORE THE TEXT POINTER
	MOV	AL,DH ;SET THE CONDITION CODES ON THE HIGH ORDER
	OR	AL,AL
	RET
global GTBYTC
GTBYTC:	CALL	CHRGTR
global GETBYT
GETBYT:	CALL	FRMEVL ;EVALUATE A FORMULA
global CONINT
CONINT:	CALL	INTFR2 ;CONVERT THE FAC TO AN INTEGER IN [D,E]
;AND SET THE CONDITION CODES BASED
;ON THE HIGH ORDER
	JZ	??L048
	JMP	FCERR ;WASN'T ERROR
??L048:
	DEC	BX ;ACTUALLY FUNCTIONS CAN GET HERE
;WITH BAD [H,L] BUT NOT SERIOUS
;SET CONDITION CODES ON TERMINATOR
	CALL	CHRGTR
	MOV	AL,DL ;RETURN THE RESULT IN [A] AND [E]
	RET
; SUBTTL EXECUTE BASIC PROGRAM ON PROM
;
; The reserve word tables have dispatch address the could be external.
; ASM86 can only output external declarations during pass 1, so we
; have to construct a chain of possible externals and check each one.
; The following macro runs through the chain and declares any undefined
; addresses as external :NEAR.  For more information, see the file
; PS1:<BASIC.ASM86>BINTRP.H
;
; DO_EXT handled by explicit extern declarations
;
