; Auto-converted mechanically from ../gw-basic/gwlist.asm
; Edit the converter or the generated source deliberately; do not hand-wave syntax changes.

; [ This translation created 10-Feb-83 by Version 4.3 ]
; .RADIX  8
%include "dwoem.inc"
; TITLE   GWLIST Copied from BINTRP.MAC
; .RADIX	10
%assign FETOK 0 ;For FE extended tokens
%assign FDTOK 0 ;For FD tokens too.  (Must have
;FETOK==1.)
;tokens.
%assign INTDEX 0 ;For Intelledex version.
%assign NMPAGE 1 ;Number of text pages (for GW
;Multi-page)
;KPOS, etc.
%assign LNREAD 0 ;For LINE READ statement
%assign MELCO 0 ;Mitsubishi Electronics Co.
%assign SIRIUS 0
%assign MCI 0
%assign ZENITH 0 ;ZENITH 8086
%assign TETRA 0
%assign CPM86 0
%assign HAL 0
%assign GENFLS 0
%assign PANDBL 0
%assign TSHIBA 0
%assign SGS 0
%assign ALPS 0
%assign ALPCPM 0
%assign GENWID 0
%assign NNECBS 0
%assign CAN8 0
%assign PC8A 0
%assign FN2SW 0 ;IBMTOK versions dispatch from IBMRES.MAC
%define LABEL PC8A
%define HLPEDT PC8A
%assign OKI 0
%assign BUBL 0
%assign NORNF 0
%assign IEESLV 0
%assign TRSHHC 0
%assign OLVPPC 0
%assign NECPPC 0
%assign USA 0 ;For HHC-USA version
%assign EUROPE 0 ;For HHC-EUROPE version
;Local Switches
;
%define LTRACE ALPCPM ;trace output selectable
%define LABEL PC8A
%define HLPEDT PC8A
%define UCEMSG NNECBS ;Upper case error messages.
%define OLD86 MELCO & CPM86 ;For "old" 8086 error messages (prior
;to alignment for IBM compatibility).
%define OLDBLD ALPCPM | ALPS | OKI | HAL | PC8A | BUBL | GW | TSHIBA
%include "gio86u.inc"
%include "msdosu.inc" ;MSDOS constants
extern INIT
extern SETGSB
extern ONGSBF
%assign BUFOFS 0
%assign BUFOFS 2 ;MUST CRUNCH INTO ERALIER PLACE FOR
; SINGLE QUOTE
%define KBFLEN BUFLEN+(BUFLEN/4) ;MAKE KRUNCH BUFFER SOMEWHAT
; LARGER THAN SOURCE BUFFER (BUF)
extern NAME
extern INLIN
extern CRDO
extern CRDONZ
extern STRCMP
extern PPSWRT
extern OUTDO
extern BLTU
extern CLEARC
extern GTMPRT
extern ISLET
extern ISLET2
extern PTRGET
extern QINLIN
extern SCRTCH
extern STKINI
extern RUNC
extern RESFIN
extern PTRGT2
extern STPEND
extern SYNCHR
extern SIGN
extern PRGFIN
extern FILIND
extern FILINP
extern INDSKC
extern LRUN
extern INXHRT
extern ZERO
extern MOVE
extern FOUT
extern FIN
extern PUSHF
extern MOVFR
extern MOVRF
extern MOVRM
extern INPRT
extern LINPRT
extern MOVFM
extern MOVMF
extern INRART
extern NEG
extern FREFAC
extern FRETMS
extern STRCPY
extern GETSTK
extern STRLIT
extern STRLT2
extern STRLT3
extern STRLTI
extern STROUT
extern STRPRT
extern STROUI
extern GETSPA
extern PUTNEW
extern STOP
extern OMERR
extern REASON
extern INSTR
extern PRINUS
extern PUTTMP
extern FOUTH
extern FOUTO
extern STRO$
extern STRH$
extern STRNG$
extern TON
extern TOFF
extern SPACE$
extern SIGNS
extern UMULT
extern SIGNC
extern POPHRT
extern FINLPT
extern VMOVFA
extern VMOVAF
extern ISIGN
extern VSIGN
extern VDFACS
extern VMOVMF
extern VMOVFM
extern FRCINT
extern FRCDBL
extern FRCSNG
extern VNEG
extern PUFOUT
extern DCXBRT
extern IADD
extern FINDBL
extern VMOVE
extern VALINT
extern VALSNG
extern FRCSTR
extern CHKSTR
extern MAKINT
extern MOVE1
extern SCNSEM
extern WHILE
extern WEND
extern CALLS
extern PROCHK
extern WRITE
;The following block of externals was added on Dec 19, 1982 when BINTRP was
; Split up after the freeze of GW-BASIC Version 1.0
; This Split-up was not reflected in the PS1:<BASIC>BINTRP.MAC source.
; See Tom Corbett if you have any questions.
;
extern MEMSIZ
extern FRETOP
extern VARTAB
extern STREND
extern TXTTAB
extern ARYTAB
extern CURLIN
extern DOT
extern DATLIN
extern NLONLY
extern ERRLIN
extern ERRTXT
extern MRGFLG
extern CHNFLG
extern SAVSTK
extern SAVTXT
extern OLDLIN
extern NXTLIN
extern OLDTXT
extern ONELIN
extern ONEFLG
extern CNTOFL
extern TRCFLG
extern CONSAV
extern CONTXT
extern CONTYP
extern NUMCON
extern CONLO
extern AUTFLG
extern AUTLIN
extern AUTINC
extern KBUF
extern BUFMIN
extern BUF
extern PTRFIL
extern PTRFLG
extern DORES
extern VALTYP
extern FACLO
extern DFACLO
extern FAC
extern TEMP
extern TEMP2
extern TEMP3
extern TEMPA
extern DSCTMP
extern TEMPST
extern OPRTYP
extern SUBFLG
extern FVALSV
extern DEFTBL
extern FLGINP
extern FLGSCN
extern OVCSTR
extern INPPAS
extern USRTAB
extern DONUM
extern ENDPRG
extern ENDFOR
extern DATPTR
extern FLGOVC
extern ERRFLG
extern SAVSEG
extern PRMLN2
extern PARM2
extern PRMLEN
extern PRMSTK
extern PARM1
extern FUNACT
extern NOFUNS
extern OPTVAL
extern OPTFLG
extern RNDX
extern INEG2
extern FADD
extern DOL_OVMSG
extern ERRTAB
extern REDDY
extern ERRFAO
extern ERRFAE
;ERRUE+DSKERR-NONDSK
;DSKERR-NONDSK
;The following externs are defined in GWMAIN.MAC
;
extern CHRGTR
extern READY
extern STPRDY
extern ISFLIO
extern CONFC1
extern DEPTR
extern FINI
extern FCERR
extern FNDLIN
extern SCNLIN
;The following externs are defined in GWEVAL.MAC
;
extern MAKUPL
extern MAKUPS
extern GETYPR
extern OCTCNS
extern DOCNVF
extern ISMID$
extern FRMEVL
extern FRMCHK
extern GETINT
extern GETBYT
extern GETIN2
extern SNGFLT
; SUBTTL ROM VERSION INITALIZATION, AND CONSTANTS
;
; The reserved word tables are in another module.  Consequently
; many things must be declared external.  All of these things
; are in the code segement or are absolutes (like tokens).
; I.e., they are not in the data segment.
;
extern ALPTAB
extern STMDSP
extern POS
extern PRINT
extern RESLST
extern SPCTAB
; SUBTTL EXTENDED LIST, DELETE, LLIST
global LLIST
LLIST:
	PUSH	BX
	MOV	BX,0-1
	MOV [PTRFIL], BX ;FDB pointer = LPT Pseudo FDB
	POP	BX
global LIST
LIST:
	POP	CX ;GET RID OF NEWSTT RETURN ADDR
	CALL	SCNLIN ;SCAN LINE RANGE
	PUSH	CX ;SAVE POINTER TO 1ST LINE
	CALL	PROCHK ;DONT EVEN LIST LINE #
	MOV BX, [TEMP] ;Get Text pointer
	DEC	BX
	CALL	CHRGTR
	JZ	LIST4 ;Brif LIST to CRT.
	CALL	SYNCHR
db 44 ; else must be ,"dev:"
	CALL	NAMSCN ;Crack File spec.
extern NAMSCN
extern NULOPM
	MOV	AL,MD_SQO ;OPEN FILE 0 FOR OUTPUT
	CALL	NULOPM
LIST4:	MOV	BX,65535 ;DONT ALLOW ^C TO CHANGE
	MOV [CURLIN], BX ;CONTINUE PARAMETERS
	POP	BX ;GET POINTER TO LINE
	POP	DX ;GET MAX LINE # OFF STACK
	MOV	CL,byte [BX] ;[B,C]=THE LINK POINTING TO THE NEXT LINE
	INC	BX
	MOV	CH,byte [BX]
	INC	BX
	MOV	AL,CH ;SEE IF END OF CHAIN
	OR	AL,CL
	JNZ	??L000
	JMP	READY ;LAST LINE, STOP.  
??L000:
extern POLKEY
	CALL	POLKEY ;check CTL C, queue typeahead
	PUSH	CX ;SAVE LINK
	MOV	CL,byte [BX] ;PUSH THE LINE #
	INC	BX
	MOV	CH,byte [BX]
	INC	BX
	PUSH	CX
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;GET LINE # INTO [H,L]
	XCHG	BX,DX ;GET MAX LINE IN [H,L]
	CMP	BX,DX ;PAST LAST LINE IN RANGE?
	POP	CX ;TEXT POINTER TO [B,C]
	JAE	??L001
	JMP	STPRDY ;IF PAST, THEN DONE LISTING.
??L001:
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;SAVE MAX ON BOTTOM OF STACK
	PUSH	BX ;SAVE LINK ON TOP
	PUSH	CX ;SAVE TEXT POINTER BACK
	XCHG	BX,DX ;GET LINE # IN [H,L]
	MOV [DOT], BX ;SAVE FOR LATER EDIT OR LIST
;AND WE WANT [H,L] ON THE STACK
	CALL	LINPRT ;PRINT AS INTEGER WITHOUT LEADING SPACE
	POP	BX
	MOV	AL,byte [BX] ;GET BYTE FROM LINE
	CMP	AL,9 ;IS IT A TAB?
	JZ	NOSPAL ;THEN DONT PRINT SPACE
	MOV	AL," "
	CALL	OUTDO ;PRINT A SPACE AFTER THE LINE #
NOSPAL:	CALL	BUFLIN ;UNPACK THE LINE INTO BUF
	MOV	BX,BUF ;POINT AT THE START OF THE UNPACKED CHARACTERS
	CALL	LISPRT ;PRINT THE LINE
	CALL	CRDO ;PRINT CRLF
	JMP	LIST4 ;GO BACK FOR NEXT LINE
global LISPRT
LISPRT:
	MOV	AL,byte [BX]
	CMP	AL,10
	JNZ	??L002
	CALL	LISEOL ;erase to end-of-line after LF and 0
??L002:
	OR	AL,AL
	JNZ	??L003
	CALL	LISEOL
??L003:
	JNZ	$+3
	RET ;IF =0 THEN END OF LINE
extern OUTCH1
	CALL	OUTCH1 ;OUTPUT CHAR AND CHECK FOR LF
	INC	BX ;INCR POINTER
	JMP	LISPRT ;PRINT NEXT CHAR
;Routine to output sequence to Clear to end of line if current device
; is Standard Output (CRT)
; Exit - All registers preserved.
;
LISEOL:	LAHF ; PUSH PSW
	XCHG	AL,AH
	PUSH	AX
	XCHG	AL,AH
	CALL	ISFLIO
	JZ	??L004
	JMP	LISELX ;return if listing to a file
??L004:
extern F_EDIT
	MOV AL, byte [F_EDIT] ;Save current edit mode
	LAHF ; PUSH PSW
	XCHG	AL,AH
	PUSH	AX
	XCHG	AL,AH
	MOV	AL,5 ;05=erase to end-of-line for non-IBMLIK
	MOV byte [F_EDIT], AL ;Enter edit mode(05 is control function)
	CALL	OUTDO ;output 05 to current device
	POP	AX ; POP PSW
	XCHG	AL,AH
	SAHF
	MOV byte [F_EDIT], AL ;Restore edit mode
LISELX:	POP	AX ; POP PSW
	XCHG	AL,AH
	SAHF
	RET
global BUFLIN
BUFLIN:	MOV	CX,BUF ;GET START OF TEXT BUFFER
	MOV	DH,BUFLEN ;GET ITS LENGTH INTO [D]
	XOR	AL,AL ;SET MODE OF DECRUNCH
	MOV byte [DORES], AL ;BIT0 IS QUOTE BIT1 IS DATA BIT2 IS REM
	XOR	AL,AL ;SET ON SPECIAL CHAR FOR SPACE INSERTION
	MOV byte [TEMPA], AL
	CALL	PROCHK ;ONLY PROCEED IF OK
	JMP	PLOOP2 ;START HERE
PLOOP:	INC	CX ;INCREMENT DEPOSIT PTR.
	INC	BX ;ADVANCE TEXT PTR
	DEC	DH ;BUMP DOWN COUNT
	JNZ	$+3
	RET ;IF BUFFER FULL, RETURN
global PLOOP2
PLOOP2:
	MOV	AL,byte [BX] ;GET CHAR FROM BUF
	OR	AL,AL ;SET CC'S
	MOV	DI,CX
	STOSB ;SAVE THIS CHAR
	JNZ	$+3
	RET ;IF END OF SOURCE BUFFER, ALL DONE.
	CMP	AL,OCTCON ;IS IT SMALLER THAN SMALLEST EMBEDDED CONSTANT?
	JB	NTEMBL ;YES, DONT TREAT AS ONE
	CMP	AL,DBLCN1 ;IS IT EMBEDED CONSTANT?
	MOV	DL,AL ;SAVE CHAR IN [E]
	JB	PRTVAR ;PRINT LEADING SPACE IF NESC.
	CMP	AL,34 ;IS IT A QUOTATION
	JNZ	BFCHKC ;IF NOT CHECK FOR COLON
	MOV AL, byte [DORES] ;COMPLEMENT THE QUOTE BIT
	XOR	AL,1
	MOV byte [DORES], AL
	MOV	AL,34 ;RESTORE THE CHARACTER
BFCHKC:	CMP	AL,":" ;IS IT A COLON ENDING DATA?
	JNZ	NTEMBL
	MOV AL, byte [DORES] ;DON'T END IF IN QUOTE
	RCR	AL,1
	JB	QTCOLN
	RCL	AL,1
	AND	AL,253 ;TURN OFF BIT1 (DATA BIT)
	MOV byte [DORES], AL
QTCOLN:	MOV	AL,":"
NTEMBL:	OR	AL,AL ;SET CC'S
	JNS	??L005
	JMP	PLOOPR ;RESERVED WORD OF SOME KIND
??L005:
	MOV	DL,AL ;SAVE CHAR IN [E]
	CMP	AL,"." ;DOT IS PART OF VAR NAME
	JZ	PRTVAR
	CALL	TSTANM ;IS CHAR ALPHANUMERIC
	JAE	PRTVAR ;ALPHANUMERIC
	XOR	AL,AL ;MAKE SPECIAL
	JMP	PLOOPH
PRTVAR:	MOV AL, byte [TEMPA] ;WHAT DID WE DO LAST?
	OR	AL,AL ;SET CONDITION CODES
	JZ	PLOOPG ;SPECIAL, NEVER INSERT SPACE
	INC	AL ;IN RESERVED WORD?
	JNZ	PLOOPG ;NO
	MOV	AL," " ;PUT OUT SPACE BEFORE RESWORD
	MOV	DI,CX
	STOSB ;STORE IN BUFFER
	INC	CX ;INCRMENT POINTER INTO BUFFER
	DEC	DH ;SPACE LEFT?
	JNZ	$+3
	RET ;NO, DONE
PLOOPG:	MOV	AL,1 ;STORE FLAG SAYING IN VAR
PLOOPH:	MOV byte [TEMPA], AL
	MOV	AL,DL ;GET BACK CHAR WE HAD
	CMP	AL,OCTCON ;IS IT SMALLER THAN SMALLEST EMBEDDED CONSTANT?
	JB	PLOOPZ ;YES, DONT TREAT AS ONE
	CMP	AL,DBLCN1 ;IS IT EMBEDED CONSTANT?
	JAE	??L006
	JMP	NUMLIN ;YES, UNPACK IT
??L006:
PLOOPZ:	MOV	DI,CX
	STOSB ;MAKE SURE BYTE STORED AFTER SPACE
	JMP	PLOOP ;STORE IN BUFFER
PLOOPR:
	MOV AL, byte [DORES] ;SEEWHAT OUR UNCRUNCH MODE IS
	RCR	AL,1 ;THE LSB IS THE QUOTE BIT
	JB	GPLOOP
	RCR	AL,1 ;GET THE REM BIT
	RCR	AL,1 ;AND SEE IF SET
	JAE	CHKDRS ;IF NOT JUST CHECK DATA BIT
	MOV	AL,byte [BX] ;MUST SEE IF ITS SNGQTK
	CMP	AL,SNGQTK ;AND PRECEDED BY ":REM"
	PUSH	BX
	PUSH	CX ;SAVE BUFFER POINTER
	MOV	BX,NOSNGQ ;PLACE TO RETURN ON FAILURE
	PUSH	BX
	JZ	$+3
	RET
	DEC	CX
	MOV	SI,CX
	MOV	AL,[SI]
	CMP	AL,"M"
	JZ	$+3
	RET
	DEC	CX
	MOV	SI,CX
	MOV	AL,[SI]
	CMP	AL,"E"
	JZ	$+3
	RET
	DEC	CX
	MOV	SI,CX
	MOV	AL,[SI]
	CMP	AL,"R"
	JZ	$+3
	RET
	DEC	CX
	MOV	SI,CX
	MOV	AL,[SI]
	CMP	AL,":"
	JZ	$+3
	RET
	POP	AX ;GET RID OF RETURN ON FAIL ADDRESS
	POP	AX ;GET RID OF BAD BUFFER POINTER
	POP	BX ;GET BACK POINTER INTO LINE
	INC	DH ;UPDATE CHAR COUNT
	INC	DH
	INC	DH
	INC	DH
	JMP	RESEXP
NOSNGQ:	POP	CX ;GET BACK THE BUFFERPOINTER
	POP	BX ;GET BACK SOURCE LINE POINTER
	MOV	AL,byte [BX] ;GET BACK THE CHARACTER
GPLOOP:	JMP	PLOOP
DATSET:	MOV AL, byte [DORES] ;BIT INDICATING INSIDE DATA
	OR	AL,2 ;IS BIT1
SETDRS:	MOV byte [DORES], AL
	XOR	AL,AL
	RET
REMSET:	MOV AL, byte [DORES]
	OR	AL,4
	JMP	SETDRS
CHKDRS:	RCL	AL,1 ;GET DATA BIT INTO CARRY
	JB	GPLOOP
	MOV	AL,byte [BX] ;GET BACK THE CHARACTER
	CMP	AL,TOK_DATA ;NEED TO SET A BIT
	JNZ	??L007
	CALL	DATSET
??L007:
	CMP	AL,TOK_REM
	JNZ	??L008
	CALL	REMSET
??L008:
RESEXP:	MOV	AL,byte [BX]
	INC	AL ;SET ZERO IF FN TOKEN
	MOV	AL,byte [BX] ;GET CHAR BACK
	JNZ	NTFNTK ;NOT FUNCTION JUST TREAT NORMALLY
	INC	BX ;BUMP POINTER
	MOV	AL,byte [BX] ;GET CHAR
	AND	AL,0o177 ;TURN OFF HIGH BIT
NTFNTK:	INC	BX ;ADVANCE TO POINT AFTER
NTQTTK:	CMP	AL,TOK_ELSE ;ELSE?
	JNZ	NOTELS
	DEC	CX
	INC	DH
NOTELS:
	CMP	AL,TOK_WHILE ;MIGHT HAVE AN EXTRA "+" IN WHILE FORMULA
	JNZ	BFNTWH ;SO SKIP OVER IT IF ITS THERE
	MOV	AL,byte [BX] ;GET CHARACTER TO SEE IF ITS PLUSTK
	INC	BX ;ASSUME IS PLUSTK
	CMP	AL,PLUSTK ;MIGHT NOT BE PLUS IF BINARY SAVED IN
	MOV	AL,TOK_WHILE ;RESTORE TOKEN VALUE
	JZ	BFNTWH ;VERSION OF BASIC BEFORE CRUNCH CHANGED
	DEC	BX ;MOVE POINTER BACK
BFNTWH:
	PUSH	BX ;SAVE TEXT PTR.
	PUSH	CX ;SAVE DEPOSIT PTR.
	PUSH	DX ;SAVE CHAR COUNT.
extern LISTX
	CALL	LISTX ;Handle extended reserved words.
	MOV	BX,RESLST-1 ;GET PTR TO START OF RESERVED WORD LIST
	MOV	CH,AL ;SAVE THIS CHAR IN [B]
	MOV	CL,"A"-1 ;INIT LEADING CHAR VALUE
RESSR3:	INC	CL ;BUMP LEADING CHAR VALUE.
RESSR1:	INC	BX ;BUMP POINTER INTO RESLST
RESSRC:	MOV	DH,BH ;SAVE PTR TO START OF THIS RESWRD
	MOV	DL,BL
RESSR2:
db 0o56 ;FETCH FROM CODE SEGMENT
	MOV	AL,byte [BX] ;GET CHAR FROM RESLST
	OR	AL,AL ;SET CC'S
	JZ	RESSR3 ;IF END OF THIS CHARS TABLE, GO BACK & BUMP C
	LAHF
	INC	BX ;BUMP SOURCE PTR
	SAHF
	JS	??L009
	JMP	RESSR2 ;IF NOT END OF THIS RESWRD, THEN KEEP LOOKING
??L009:
db 0o56 ;FETCH FROM CODE SEGMENT
	MOV	AL,byte [BX] ;GET PTR TO RESERVED WORD VALUE
	CMP	AL,CH ;SAME AS THE ONE WE SEARCH FOR?
	JNZ	RESSR1 ;NO, KEEP LOOKING.
	XCHG	BX,DX ;SAVE FOUND PTR IN [H,L]
	CMP	AL,TOK_USR ;USR FUNCTION TOKEN?
	JZ	NOISPA ;DONT INSERT SPACE
	CMP	AL,TOK_FN ;IS IT FUNCTION TOKEN?
NOISPA:
	MOV	AL,CL ;GET LEADING CHAR
	POP	DX ;RESTORE LINE CHAR COUNT
	POP	CX ;RESTORE DEPOSIT PTR
	MOV	DL,AL ;SAVE LEADING CHAR
	JNZ	NTFNEX ;NOT "FN" EXPANSION
	MOV AL, byte [TEMPA] ;SET CC'S ON TEMPA
	OR	AL,AL
	MOV	AL,0 ;CLEAR RESWRD FLAG - MARK AS SPECIAL
	MOV byte [TEMPA], AL ;SET FLAG
	JMP	MORLNZ ;DO EXPANSION
NTFNEX:
	CMP	AL,"Z"+1 ;WAS IT A SPECIAL CHAR?
	JNZ	NTSPCH ;NON-SPECIAL CHAR
	XOR	AL,AL ;SET NON-SPECIAL
	MOV byte [TEMPA], AL
	JMP	MORPUR ;PRINT IT
NTSPCH:	MOV AL, byte [TEMPA] ;WHAT DID WE DO LAST?
	OR	AL,AL ;SPECIAL?
	MOV	AL,255 ;FLAG IN RESERVED WORD
	MOV byte [TEMPA], AL ;CLEAR FLAG
MORLNZ:	JZ	MORLN0 ;GET CHAR AND PROCEED
	MOV	AL," " ;PUT SPACE IN BUFFER
	MOV	DI,CX
	STOSB
	INC	CX
	DEC	DH ;ANY SPACE LEFT IN BUFFER
	JNZ	??L010
	JMP	PPSWRT ;NO, RETURN
??L010:
MORLN0:	MOV	AL,DL
	JMP	MORLN1 ;CONTINUE
MORPUR:
db 0o56 ;FETCH FROM CODE SEGMENT
	MOV	AL,byte [BX] ;GET BYTE FROM RESWRD
	INC	BX ;BUMP POINTER
MORLNP:	MOV	DL,AL ;SAVE CHAR
MORLN1:	AND	AL,0o177 ;AND OFF HIGH ORDER BIT FOR DISK & EDIT
	MOV	DI,CX
	STOSB ;STORE THIS CHAR
	INC	CX ;BUMP PTR
	DEC	DH ;BUMP DOWN REMAINING CHAR COUNT
	JNZ	??L011
	JMP	PPSWRT ;IF END OF LINE, JUST RETURN
??L011:
	OR	AL,DL ;SET CC'S
	JS	??L012
	JMP	MORPUR ;END OF RESWRD?
??L012:
	CMP	AL,"("+128 ;SPC( OR TAB( ?
	JNZ	NTSPCT ;NO
	XOR	AL,AL ;CLEAR FLAG
	MOV byte [TEMPA], AL ;TO INSERT SPACE AFTERWARDS
NTSPCT:
	POP	BX ;RESTORE SOURCE PTR.
	JMP	PLOOP2 ;GET NEXT CHAR FROM LINE
global TSTANM
TSTANM:	CALL	ISLET2 ;LETTER?
	JNAE	$+3
	RET ;YES
	CMP	AL,"0" ;DIGIT?
	JNB	$+3
	RET ;TOO SMALL
	CMP	AL,"9"+1 ;LAST DIGIT
	CMC ;MAKE CARRY RIGHT
	RET ;NO CARRY=DIGIT
NUMLIN:	DEC	BX ;MOVE POINTER BACK AS CHRGET INX'S
	CALL	CHRGTR ;SCAN THE CONSTANT
	PUSH	DX ;SAVE CHAR COUNT
	PUSH	CX ;SAVE DEPOSIT PTR
	PUSH	AX ;SAVE CONSTANT TYPE.
	CALL	CONFC1 ;MOVE CONSTANT INTO FAC
	POP	AX ;RESTORE CONSTANT TYPE
	MOV	CX,CONLIN ;PUT RETURN ADDR ON STACK
	PUSH	CX ;SAVE IT
	CMP	AL,OCTCON ;OCTAL CONSTANT?
	JNZ	??L013
	JMP	FOUTO ;PRINT IT
??L013:
	CMP	AL,HEXCON ;HEX CONSTANT?
	JNZ	??L014
	JMP	FOUTH ;PRINT IN HEX
??L014:
	MOV BX, [CONLO] ;GET LINE # VALUE IF ONE.
	JMP	FOUT ;PRINT REMAINING POSSIBILITIES.
CONLIN:	POP	CX ;RESTORE DEPOSIT PTR.
	POP	DX ;RESTORE CHAR COUNT
	MOV AL, byte [CONSAV] ;GET SAVED CONSTANT TOKEN
	MOV	DL,"O" ;ASSUME OCTAL CONSTANT
	CMP	AL,OCTCON ;OCTAL CONSTANT?
	JZ	SAVBAS ;YES, PRINT IT
	CMP	AL,HEXCON ;HEX CONSTANT?
	MOV	DL,"H" ;ASSUME SO.
	JNZ	NUMSLN ;NOT BASE CONSTANT
SAVBAS:
	MOV	AL,"&" ;PRINT LEADING BASE INDICATOR
	MOV	DI,CX
	STOSB ;SAVE IT
	INC	CX ;BUMP PTR
	DEC	DH ;BUMP DOWN CHAR COUNT
	JNZ	$+3
	RET ;RETURN IF END OF BUFFER
	MOV	AL,DL ;GET BASE CHAR
	MOV	DI,CX
	STOSB ;SAVE IT
	INC	CX ;BUMP PTR
	DEC	DH ;BUMP DOWN BASE COUNT
	JNZ	$+3
	RET ;END OF BUFFER, DONE
NUMSLN:
	MOV AL, byte [CONTYP] ;GET TYPE OF CONSTANT WE ARE
	CMP	AL,4 ;IS IT SINGLE OR DOUBLE PREC?
	MOV	DL,0 ;NO, NEVER PRINT TRAILING TYPE INDICATOR
	JB	TYPSET
	MOV	DL,"!" ;ASSUME SINGLE PREC.
	JZ	TYPSET ;IS CONTYP=4, WAS SINGLE
	MOV	DL,"#" ;DOUBLE PREC INDICATOR
TYPSET:
	MOV	AL,byte [BX] ;GET LEADING CHAR
	CMP	AL," " ;LEADING SPACE
	JNZ	??L015
	CALL	INXHRT ;GO BY IT
??L015:
NUMSL2:	MOV	AL,byte [BX] ;GET CHAR FROM NUMBER BUFFER
	INC	BX ;BUMP POINTER
	OR	AL,AL ;SET CC'S
	JZ	NUMDN ;IF ZERO, ALL DONE.
	MOV	DI,CX
	STOSB ;SAVE CHAR IN BUF.
	INC	CX ;BUMP PTR
	DEC	DH ;SEE IF END OF BUFFER
	JNZ	$+3
	RET ;IF END OF BUFFER, RETURN
	MOV AL, byte [CONTYP] ;GET TYPE OF CONSTANT TO BE PRINTED
	CMP	AL,4 ;TEST FOR SINGLE OR DOUBLE PRECISION
	JB	NUMSL2 ;NO, WAS INTEGER
	LAHF
	DEC	CX ;PICK UP SAVED CHAR
	SAHF
	MOV	SI,CX
	MOV	AL,[SI] ;EASIER THAN PUSHING ON STACK
	LAHF
	INC	CX ;RESTORE TO POINT WHERE IT SHOULD
	SAHF
	JNZ	DBLSCN ;IF DOUBLE, DONT TEST FOR EMBEDED "."
	CMP	AL,"." ;TEST FOR FRACTION
	JZ	ZERE ;IF SINGLE & EMBEDED ., THEN DONT PRINT !
DBLSCN:	CMP	AL,"D" ;DOUBLE PREC. EXPONENT?
	JZ	ZERE ;YES, MARK NO VALUE TYPE INDICATOR NESC.
	CMP	AL,"E" ;SINGLE PREC. EXPONENT?
	JNZ	NUMSL2 ;NO, PROCEED
ZERE:	MOV	DL,0 ;MARK NO PRINTING OF TYPE INDICATOR
	JMP	NUMSL2 ;KEEP MOVING NUMBER CHARS INTO BUF
NUMDN:
	MOV	AL,DL ;GET FLAG TO INDICATE WHETHER TO INSERT
	OR	AL,AL ;A "D" AFTER DOUBLE PREC. #
	JZ	NOD ;NO, DONT INSERT IT
	MOV	DI,CX
	STOSB ;SAVE IN BUFFER
	INC	CX ;BUMP POINTER
	DEC	DH ;DECRMENT COUNT OF CHARS LEFT IN BUFFER
	JNZ	$+3
	RET ;=0, MUST TRUNCATE LIST OF THIS LINE.
NOD:
	MOV BX, [CONTXT] ;GET BACK TEXT POINTER AFTER CONSTANT
	JMP	PLOOP2 ;GET NEXT CHAR
;
; THE FOLLOWING CODE IS FOR THE DELETE RANGE
; COMMAND. BEFORE THE LINES ARE DELETED, 'OK'
; IS TYPED.
;
global DELETE
DELETE:
	CALL	SCNLIN ;SCAN LINE RANGE
	PUSH	CX
	CALL	DEPTR ;CHANGE POINTERS BACK TO NUMBERS
	POP	CX
	POP	DX ;POP MAX LINE OFF STACK
	PUSH	CX ;SAVE POINTER TO START OF DELETION
;FOR USE BY CHEAD AFTER FINI
	PUSH	CX ;SAVE POINTER TO START OF 1ST LINE
	CALL	FNDLIN ;FIND THE LAST LINE
	JAE	FCERRG ;MUST HAVE A MATCH ON THE UPPER BOUND
	MOV	DH,BH ;[D,E]=POINTER AT THE START OF THE LINE
	MOV	DL,BL ;BEYOND THE LAST LINE IN THE RANGE
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;SAVE THE POINTER TO THE NEXT LINE
	PUSH	BX ;SAVE THE POINTER TO THE START OF
;THE FIRST LINE IN THE RANGE
	CMP	BX,DX ;MAKE SURE THE START COMES BEFORE THE END
FCERRG:	JNAE	??L016
	JMP	FCERR ;IF NOT, "ILLEGAL FUNCTION CALL"
??L016:
;DELETE must now be at EOL
extern EOSCHK
	MOV BX, [TEMP] ;Get text pointer
	CALL	EOSCHK ;Check for end of statement
	MOV	BX,REDDY ;PRINT "OK" PREMATURELY
	CALL	STROUT
	POP	CX ;GET POINTER TO FIRST IN [B,C]
	MOV	BX,FINI ;GO BACK TO FINI WHEN DONE
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;[H,L]=POINTER TO THE NEXT LINE
; ERASE A LINE FROM MEMORY
; [B,C]=START OF LINE BEING DELETED
; [H,L]=START OF NEXT LINE
;
global DEL
DEL:	XCHG	BX,DX ;[D,E] NOW HAVE THE POINTER TO THE LINE
;BEYOND THIS ONE
	MOV BX, [VARTAB] ;COMPACTIFYING TO VARTAB
MLOOP:	MOV	SI,DX
	MOV	AL,[SI]
	MOV	DI,CX
	STOSB ;SHOVING DOWN TO ELIMINATE A LINE
	INC	CX
	INC	DX
	CMP	BX,DX ;DONE COMPACTIFYING?
	JNZ	MLOOP ;NO
	MOV	BX,CX
;Clear SCALARS and ARRAYS incase we are replacing line which may force
; garbage collection in BLTU
	MOV [VARTAB], BX
	MOV [ARYTAB], BX
	MOV [STREND], BX
	RET
