; Auto-converted mechanically from gw-basic/maclng.asm
; Edit the converter or the generated source deliberately; do not hand-wave syntax changes.

; [ This translation created 10-Feb-83 by Version 4.3 ]
; .RADIX  8
%include "dwoem.inc"
; TITLE   MACLNG - MACRO LANGUAGE DRIVER
;
; MICROSOFT GRAPHICS AND SOUND MACRO LANGUAGES
;
%define TSHIBA 0
%define ALPCPM 0
global FETCHR
global FETCHZ
global DECFET
global VALSCN
global VALSC2
global VARGET
global NEGD
extern FCERR
extern FRESTR
extern FRCINT
extern FRMEVL
extern ISVAR
extern MCLLEN
extern MCLPTR
extern BUF
extern MCLTAB
global MACLNG
global MCLXEQ
extern GETBCD
MACLNG:	MOV	[MCLTAB],DX ;SAVE POINTER TO COMMAND TABLE
	CALL	FRMEVL ;EVALUATE STRING ARGUMENT
	PUSH	BX ;SAVE TXTPTR TILL DONE
	MOV	DX,0 ;PUSH DUMMY ENTRY TO MARK END OF STK
	PUSH	DX ;DUMMY ADDR
	PUSH	AX ;DUMMY LENGTH
MCLNEW:	CALL	FRESTR
	CALL	GETBCD ;GET LENGTH & POINTER
	MOV	AL,CH
	OR	AL,CL
	JZ	MCLOOP ;Don't Push if addr is 0
	MOV	AL,DH
	OR	AL,AL
	JZ	MCLOOP ; or if Len is 0...
	PUSH	CX ;PUSH ADDR OF STRING
	MOV	AL,DH ;PUT IN [AL]
	PUSH	AX
MCLOOP:	POP	AX ;GET LENGTH OFF STACK
	MOV	byte [MCLLEN],AL
	POP	BX ;GET ADDR
	OR	BX,BX ;SEE IF LAST ENTRY
	JNZ	??L000
	JMP	POPTRT
??L000: ;ALL FINISHED IF ZERO
	MOV	[MCLPTR],BX ;SET UP POINTER
MCLSCN:	CALL	FETCHR ;GET A CHAR FROM STRING
	JZ	MCLOOP ;END OF STRING - SEE IF MORE ON STK
	ADD	AL,AL ;PUT CHAR * 2 INTO [C]
	MOV	CL,AL
	MOV	BX,MCLTAB ;POINT TO COMMAND TABLE
MSCNLP:
db 0o56 ;CS OVERRIDE
	MOV	AL,byte [BX] ;GET CHAR FROM COMMAND TABLE
	ADD	AL,AL ;CHAR = CHAR * 2 (CLR HI BIT FOR CMP)
GOFCER:	JNZ	??L001
	CALL	FCERR ;END OF TABLE.
??L001:
	CMP	AL,CL ;HAVE WE GOT IT?
	JZ	MISCMD ;YES.
	INC	BX ;MOVE TO NEXT ENTRY
	INC	BX
	INC	BX
	JMP	MSCNLP
MISCMD:
	MOV	CX,MCLSCN ;RETURN TO TOP OF LOOP WHEN DONE
	PUSH	CX
db 0o56 ;CS OVERRIDE
	MOV	AL,byte [BX] ;SEE IF A VALUE NEEDED
	MOV	CL,AL ;PASS GOTTEN CHAR IN [C]
	ADD	AL,AL
	JAE	MNOARG ;COMMAND DOESN'T REQUIRE ARGUMENT
	OR	AL,AL ;CLEAR CARRY
	RCR	AL,1 ;MAKE IT A CHAR AGAIN
	MOV	CL,AL ;PUT IN [C]
	PUSH	CX
	PUSH	BX ;SAVE PTR INTO CMD TABLE
	CALL	FETCHR ;GET A CHAR
	MOV	DX,1 ;DEFAULT ARG=1
	JNZ	??L002
	JMP	VSNAR0 ;NO ARG IF END OF STRING
??L002:
	CALL	ISLET2 ;SEE IF POSSIBLE LETTER
	JNAE	??L003
	JMP	VSNARG
??L003:
	CALL	VALSC3 ;GET THE VALUE
	STC ;SET CARRY TO FLAG USING NON-DEFAULT
	JMP	ISCMD3
VSNARG:	CALL	DECFET ;PUT CHAR BACK INTO STRING
VSNAR0:	OR	AL,AL ;CLEAR CARRY
ISCMD3:	POP	BX
	POP	CX ;GET BACK COMMAND CHAR
MNOARG:	INC	BX ;POINT TO DISPATCH ADDR
db 0o56 ;CS OVERRIDE
	MOV	BX,[BX] ;GET ADDRESS INTO HL
	JMP	BX ;DISPATCH
FETCHZ:	CALL	FETCHR ;GET A CHAR FROM STRING
	JZ	GOFCER ;GIVE ERROR IF END OF LINE
	RET
FETCHR:	PUSH	BX
FETCH2:	MOV	BX,MCLLEN ;POINT TO STRING LENGTH
	MOV	AL,byte [BX]
	OR	AL,AL
	JZ	POPTRT ;RETURN Z=0 IF END OF STRING
	DEC	byte [BX] ;UPDATE COUNT FOR NEXT TIME
	MOV	BX,MCLPTR ;GET PTR TO STRING
	MOV	AL,byte [BX] ;GET CHARACTER FROM STRING
	INC	BX ;UPDATE PTR FOR NEXT TIME
	MOV	[MCLPTR],BX
	CMP	AL," " ;SKIP SPACES
	JZ	FETCH2
	CMP	AL,96 ;CONVERT LOWER CASE TO UPPER
	JB	POPTRT
	SUB	AL,32 ;DO CONVERSION
POPTRT:	POP	BX
	RET
DECFET:	PUSH	BX
	MOV	BX,MCLLEN ;INCREMENT LENGTH
	INC	byte [BX]
	MOV	BX,MCLPTR ;BACK UP POINTER
	DEC	BX
	MOV	[MCLPTR],BX
	POP	BX
	RET
VALSCN:	CALL	FETCHZ ;GET FIRST CHAR OF ARGUMENT
VALSC3:	CMP	AL,"=" ;NUMERIC?
	JNZ	??L004
	JMP	VARGET
??L004:
	CMP	AL,"+" ;PLUS SIGN?
	JZ	VALSCN ;THEN SKIP IT
	CMP	AL,"-" ;NEGATIVE VALUE?
	JNZ	VALSC2
	MOV	DX,NEGD ;IF SO, NEGATE BEFORE RETURNING
	PUSH	DX
	JMP	VALSCN ;EAT THE "-"
VALSC2:
	MOV	DX,0 ;INITIAL VALUE OF ZERO
NUMLOP:
	CMP	AL,0o54 ;COMMA
	JZ	DECFET ;YES, BACK UP AND RETURN
	CMP	AL,0o73 ;SEMICOLON?
	JNZ	$+3
	RET ;YES, JUST RETURN
	CMP	AL,"9"+1 ;NOW SEE IF ITS A DIGIT
	JAE	DECFET ;IF NOT, BACK UP AND RETURN
	CMP	AL,"0"
	JB	DECFET
	MOV	BX,0 ;[HL] is accumulator
	MOV	CH,10 ;[HL]=[DE]*10
NUML01:	ADD	BX,DX
	JB	SCNFC ;overflow - JMP Function Call Error
	DEC	CH
	JNZ	NUML01
	SUB	AL,"0" ;ADD IN THE DIGIT
	MOV	DL,AL
	MOV	DH,0
	ADD	BX,DX
	JB	SCNFC ;overflow - JMP Function Call Error
	XCHG	BX,DX ;VALUE SHOULD BE IN [DE]
	CALL	FETCHR ;GET NEXT CHAR
	JNZ	NUMLOP ;branch if not end of string
	RET
SCNVAR:
extern VALTYP
extern RETVAR
;Allow VARPTR$(variable) for BASCOM compatibility
;
	MOV	BX,MCLPTR ;Get string pntr
	MOV	AL,byte [BX] ;possible VALTYP if string created by VARPTR$
	CMP	AL,9 ;If .gt. 8 then not VARPTR$ string
	JAE	SCNVR2 ;Brif not VARPTR$ candidate
	MOV	AL,byte [MCLLEN] ;Get str len
	SUB	AL,3 ;at least 3 bytes if it was created by VARPTR$
	JB	SCNVR2 ;else let SCNVAR generate FCERR for bad var name
	MOV	byte [MCLLEN],AL ;len -3
	MOV	AL,byte [BX] ;assume Byte 1 is Type
	MOV	byte [VALTYP],AL ;so store in FAC
	INC	BX
	MOV	DL,byte [BX]
	INC	BX
	MOV	DH,byte [BX] ;[DE] = Var address.
	INC	BX
	MOV	[MCLPTR],BX ;New pntr
	JMP	RETVAR ;Go return value in FAC
SCNVR2:
	CALL	FETCHZ ;MAKE SURE FIRST CHAR IS LETTER
	MOV	DX,BUF ;PLACE TO COPY NAME FOR PTRGET
	PUSH	DX ;SAVE ADDR OF BUF FOR "ISVAR"
	MOV	CH,40 ;COPY MAX OF 40 CHARACTERS
	CALL	ISLET2 ;MAKE SURE IT'S A LETTER
	JB	SCNFC ;FC ERROR IF NOT LETTER
SCNVLP:	MOV	DI,DX
	STOSB ;STORE CHAR IN BUF
	INC	DX
	CMP	AL,0o73 ;A SEMICOLON?
	JZ	SCNV2 ;YES - END OF VARIABLE NAME
	CALL	FETCHZ ;GET NEXT CHAR
	DEC	CH
	JNZ	SCNVLP
SCNFC:	CALL	FCERR ;ERROR - VARIABLE TOO LONG
SCNV2:	POP	BX ;GET PTR TO BUF
	JMP	ISVAR ;GO GET ITS VALUE
VARGET:	CALL	SCNVAR ;SCAN & EVALUATE VARIABLE
	CALL	FRCINT ;MAKE IT AN INTEGER
	XCHG	BX,DX ;IN [DE]
	RET
extern GETSTK
MCLXEQ:	CALL	SCNVAR ;SCAN VARIABLE NAME
	MOV	AL,byte [MCLLEN] ;SAVE CURRENT STRING POS & LENGTH
	MOV	BX,MCLPTR
	POP	SI ;XTHL
	XCHG	SI,BX
	PUSH	SI ;POP OFF RET ADDR, PUSH MCLPTR
	PUSH	AX
	MOV	CL,2 ;MAKE SURE OF ROOM ON STACK
	CALL	GETSTK
	JMP	MCLNEW
NEGD:
db 0o367, 0o332 ;NEG DX,DX
	RET
ISLET2:	CMP	AL,"A"
	JB	ISLETX ;TOO SMALL FOR LETTER
	CMP	AL,"Z"+1
	CMC ;SET CARRY IF NOT LETTER
ISLETX:	RET
