; Auto-converted mechanically from ../gw-basic/next86.asm
; Edit the converter or the generated source deliberately; do not hand-wave syntax changes.

; [ This translation created 10-Feb-83 by Version 4.3 ]
; .RADIX  8
%include "dwoem.inc"
; TITLE NEXT86 CODE
; .RADIX	8
;****************************************************************
;
; A "FOR" ENTRY ON THE STACK HAS THE FOLLOWING FORMAT:
;
; LOW ADDRESS
;       TOKEN ($FOR IN HIGH BYTE)  1 BYTES
;       A POINTER TO THE LOOP VARIABLE  2 BYTES
;       UNDER ANSI & LENGTH=2, TWO BYTES GIVING TEXT POINTER OF  
;       MATCHING "NEXT"
;       A BYTE REFLECTING THE SIGN OF THE INCREMENT 1 BYTE
;       UNDER LENGTH=2, A BYTE MINUS FOR INTEGER AND 
;       POSITIVE FOR FLOATING "FOR'S"
;       THE STEP 4 BYTES
;       THE UPPER VALUE 4 BYTES
;       THE LINE # OF THE "FOR" STATEMENT 2 BYTES
;       A TEXT POINTER INTO THE "FOR" STATEMENT 2 BYTES
; HIGH ADDRESS
;
; TOTAL 16-19 BYTES
;
;*****************************************************************
extern CHRGTR
extern DCOMPR
extern FADDS
extern FCOMP
extern FNDFOR
extern IADD
extern ICMPA
extern MOVFM
extern MOVMF
extern MOVRM
extern NEWSTT
extern NFERR
extern NXTCON
extern OVERR
extern PTRGET
global NEXT
global NEXTS
extern NXTFLG
extern FVALSV
extern NXTTXT
extern FACLO
extern SAVSTK
extern TEMP
extern VALTYP
extern CURLIN
NF1:	JMP	NFERR
NEXT:
	LAHF ;FLAGS TO AH
	XCHG	AH,AL
	PUSH	AX
	MOV	AL,0o1
	JMP	NEXTS1
NEXTS:	XOR	AL,AL ;FLAG THAT "FOR IS USING "NEXT
NEXTS1:	MOV	byte [NXTFLG],AL
	POP	AX
	XCHG	AL,AH
	SAHF
	MOV	DX,0o0
NEXTC:
	MOV	word [NXTTXT],BX ;SAVE STARTING TEXT POINTER
	JZ	NEXTC1
	CALL	PTRGET
NEXTC1:	MOV	word [TEMP],BX ;SAVE PTR TO LOOP VARIABLE
	CALL	FNDFOR ;TRY TO FING A "FOR ENTRY
	JNZ	NF1 ;NEXT W/O FOR ERROR
	MOV	SP,BX ;SETUP STACK BY  CHOPPING HERE
	MOV	SI,word [NXTTXT]
	CMP	word [BX+0o0],SI ;COMPARE TEXT POINTERS AT THE START
	JNZ	NF1 ;OF THIS "NEXT WITH THIS NEXT
	PUSH	DX ;PUSH STEP ONTO THE STACK
	MOV	AH,byte [BX+0o2] ;
	PUSH	AX
	PUSH	DX ;PTR. TO LOOP VAR. ON STACK
	ADD	BX,0o4
	TEST	byte [BX-0o1],0o200 ;SEE IF INTEGER FOR
	JS	INTNXT ;IF INTEGER HANDLE SEPARATELY
	MOV	CX,0o2 ;
	CLD ;DF=0 SO MOVW WILL INCREMENT
	MOV	SI,BX
	MOV	DI,FACLO
 REP	MOVSW ;GET LOOP VARIABLE
	POP	BX ;PTR TO FOR ENTRY
	PUSH	SI ;
	PUSH	BX
	TEST	byte [NXTFLG],0o377
	JNZ	NXTDO
	MOV	SI,FVALSV ;FETCH INITIAL VALUE
	SUB	DI,0o4 ;POINT DI BACK TO FACLO
	MOV	CX,0o2 ;TWO WORD MOVE
 REP	MOVSW
	XOR	AL,AL ;CONTINUE "NEXT" WITH INITIAL VALUE
	JZ	NXTDOA ;
NXTDO:	CALL	FADDS
NXTDOA:	POP	DI ;POP PTR TO LOOP VARIABLE
	MOV	SI,FACLO ;WILL MOVE FAC TO THERE
	MOV	CX,0o2
	CLD
 REP	MOVSW
	POP	SI ;GET ENTRY PTR.
	MOV	DX,word [SI+0o0]
	MOV	CX,word [SI+0o2]
	ADD	SI,0o4
	PUSH	SI ;SAVE ENTRY PTR.
	CALL	FCOMP ;COMPARE THE NOS. RETURNING
;377 IF FAC LESS THAN REGS,0 IF =
;AND 1 IF GREATER 
	JMP	FINNXT ;SKIP INTEGER CODE
INTNXT:	ADD	BX,0o4 ;SKIP 4 DUMMY BYTES
	MOV	CX,word [BX+0o0] ;FETCH STEP TO CX
	INC	BX
	INC	BX
	POP	SI ;PTR TO LOOP VARIABLE
	MOV	DX,word [SI+0o0]
	TEST	byte [NXTFLG],0o377 ;SEE IF "FOR IS USING "NEXT CODE
	JNZ	INXTDO ;NO , JUST CONTINUE
	MOV	DX,word [FVALSV] ;GET THE INITIAL VALUE
	JMP	IFORIN ;CONTINUE FIRST ITERATION CHECK
INXTDO:	ADD	DX,CX
	JO	OV1
IFORIN:
	MOV	word [SI+0o0],DX
	PUSH	DX ;SAVE THE VALUE OF THE LOOP VAR.
	MOV	DX,word [BX+0o0] ;
	INC	BX
	INC	BX
	POP	AX
	PUSH	BX
	CALL	ICMPA ;COMPARE (AX) WITH (DX)
FINNXT:
	POP	BX ;POP "FOR ENTRY PTR
	POP	CX ;GET SGN OF INCREMENT
	SUB	AL,CH ;SUBTRACT THE INCREMENTS SIGN FROM
;THAT OF (CURRENT VAL-FINAL VAL)
	CALL	MOVRM ;GET LINE # OF "FOR INTO DX AND
;TEXT PTR OF "FOR INTO CX
	JZ	LOOPDN ;JUMP IF DONE
	MOV	word [CURLIN],DX ;STORE LINE NO.
	MOV	DX,CX ;SETUP THE TEXT PTR
	XCHG	DX,BX
	JMP	NXTCON
LOOPDN:	MOV	SP,BX ;ELIMINATE FOR ENTRY & SAVE UPDATED
	MOV	word [SAVSTK],BX ;STACK
	MOV	BX,word [TEMP] ;RESTORE TEXT PTR
	CMP	byte [BX+0o0],0o54 ;COMMA?
	JNZ	NS1 ;"NEXT
LOOPD1:	MOV	byte [NXTFLG],0o377 ;Set NXTFLG non-zero since NEXT couldn't
;have been called by FOR in this case
	CALL	CHRGTR ;Skip comma
	MOV	DX,SP ;[DX]=[SP] which will never match
;any VARPTR (see FNDFOR)
	CALL	NEXTC ;Process Next NEXT
OV1:	JMP	OVERR
NS1:	JMP	NEWSTT
